### ISSUE TITLE
Manually defining relations [plugin available]

### ISSUE THREAD

**Issue by kuinak** [graphile/graphile-engine#174]
Let's say I have a couple tables that reference each other, however the foreign key constraint is not enforced by the database:
```
create table person (
  id serial primary key,
  name varchar not null,
  about text,
  email varchar not null unique,
  created_at timestamp default current_timestamp
);

create table post (
  id serial primary key,
  headline text not null,
  body text,
  -- no actual referential integrity here
  person_id int4 not null
);
```

Is there a way I can manually define this relation in PostGraphile to allow GraphQL queries like:
```
{
  allPosts {
    nodes {
      headline
      body

      personByPersonId {
        id
        name
        about
      }
    }
  }
}
```

**Comment by benjie** [comment]
You may add a plugin to do so. This is the plugin that is responsible for adding the `personByPersonId` relation:

https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/plugins/PgForwardRelationPlugin.js

and this one for adding the (unshown) `postsByPersonId` relation:

https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js

The plugins are not as complex as they look - let me know once you've looked them over if you're interested in going that route - if so I could offer some pointers on how to build your new plugin.

In the future we might enable this functionality via smart comments, but we've not got that far yet (and there are much higher priority tasks to do first). Actually... if you wanted to write the plugin to do this with smart comments that'd be pretty cool.

Let me know how you plan to proceed.

**Comment by tngmichael** [comment]
Hi, I'm trying to make first plugin based on this issue requirement (and gitter too :smile:). Can you take a look @benjie  
https://github.com/tngmichael/pg-relation-tag-plugin/blob/master/index.js

See ASK notes I need your help, currently I write for forward relation. Somehow I managed to get working with simple tag e.g `@references my_schema.people.id`

**Comment by tngmichael** [comment]
Updated, now can support backward relation too

**Comment by abrkn** [comment]
I have this issue as well. I have a view that returns the same columns as a table. Any ideas?

**Comment by benjie** [comment]
I'm planning on making support for views a lot more like tables. To accelerate development, you can either back my Patreon: https://www.patreon.com/benjie or if you need it really fast you can sponsor development of the feature you need.

**Comment by abrkn** [comment]
![image](https://user-images.githubusercontent.com/843958/47492146-8a219f80-d876-11e8-894e-6d988b6f216f.png)

Great to hear you're working on the view feature. I'm using Graphile for a hobby project, but am backing you on Patreon now.

I'll use a workaround for now (`returns setof`) and hope my server doesn't die from pagination.

**Comment by benjie** [comment]
Really appreciate that @abrkn - thanks! My short term list once 4.1 is out is basically improving the docs site, creating some basic example boilerplates, and then hopefully on to views. Views is going to be a big task!

**Comment by abrkn** [comment]
I can imagine. Graphile is magic to me. I don't even want to guess how the resolving is done :-)

**Comment by benjie** [comment]
This is supported as of v4.2.0: https://github.com/graphile/postgraphile/releases/tag/v4.2.0

https://www.graphile.org/postgraphile/smart-comments/#constraints
