### ISSUE TITLE
makeExtendSchemaPlugin: Add support for more GraphQL base types (GraphQLScalarType, etc)

### ISSUE THREAD

**Issue by benjie** [graphile/graphile-engine#238]
- GraphQLScalarType
- GraphQLInterfaceType
- GraphQLUnionType

**Comment by benjie** [comment]
Not sure, I’ve not really thought about it yet. Scalar should probably be pretty easy. The problem with interface is how it interfaces with the look-ahead features. If you’re not using that then it’s probably fairly easy too. Feel free to ping me on Discord for feedback as you go if you’re looking at implementing this 👍

**Comment by benjie** [comment]
This was completed a while back. It doesn't solve the problem of actually using them with database types, but for pure GraphQL types they work and are used in e.g. `@graphile/postgis`

**Comment by saerdnaer** [comment]
To clarify: https://github.com/graphile/graphile-engine/pull/480 did implement `GraphQLScalarType` and `GraphQLUnionType`, but not `GraphQLInterfaceType`.

**Comment by benjie** [comment]
Quite right
