### ISSUE TITLE
potentially a bug in docs regarding finding/testing indexes on constraints

### ISSUE THREAD

**Issue by pyramation** [graphile/graphile-engine#308]
Referencing these docs: https://www.graphile.org/postgraphile/postgresql-indexes/#advice---foreign-key-indexes

I know this code came from a medium article, perhaps it was adapted since the author's original code had some functions defined in it (https://medium.com/@awesboss/how-to-find-missing-indexes-on-foreign-keys-2faffd7e6958).

The `indkey` is an `int2vector` (https://www.postgresql.org/docs/current/static/catalog-pg-index.html), and casting it the way it was done in the docs seemingly wasn't working for me. It could be a postgres version issue? I'm running 10.3.

I made 3 changes regarding the `indkey` column so we can properly compare it to the `conkey`:

* in the first select inside the RTE `string_to_array(ix.indkey::text, ' ')::smallint[] as indkey`
* in the second line of the final where clause: `AND conkey = indkey`
* in the third line of the final where clause: `OR (array_length(indkey, 1) > 1 AND indkey @> conkey)`

Here is my working code

```sql
WITH indexed_tables AS (
select
    ns.nspname,
    t.relname as table_name,
    i.relname as index_name,
    array_to_string(array_agg(a.attname), ', ') as column_names,
    ix.indrelid,
    string_to_array(ix.indkey::text, ' ')::smallint[] as indkey
FROM pg_class i
JOIN pg_index ix ON i.OID = ix.indrelid
JOIN pg_class t ON ix.indrelid = t.oid
JOIN pg_namespace ns ON ns.oid = t.relnamespace
JOIN pg_attribute a ON a.attrelid = t.oid
where a.attnum = ANY(ix.indkey)
and t.relkind = 'r'
and nspname not in ('pg_catalog')
group by
    ns.nspname,
    t.relname,
    i.relname,
    ix.indrelid,
    ix.indkey
order by
    ns.nspname,
    t.relname,
    i.relname,
    ix.indrelid,
    ix.indkey
)
SELECT
  conrelid::regclass,
  conname,
  reltuples::bigint
  FROM pg_constraint pgc
  JOIN pg_class ON (conrelid = pg_class.oid)
  WHERE contype = 'f'
  AND NOT EXISTS(
    SELECT 1
    FROM indexed_tables
    WHERE indrelid = conrelid
    AND conkey = indkey
   OR (array_length(indkey, 1) > 1 AND indkey @> conkey)
  )
  ORDER BY reltuples DESC;
```

fyi, from my research on how to properly cast the types: https://stackoverflow.com/questions/28072583/how-can-i-test-if-int2vector-contains-exactly-one-specific-value

**Comment by pyramation** [comment]
https://github.com/graphile/graphile.github.io/pull/76 @benjie I made a PR, sorry I made this issue on the wrong repo

**Comment by benjie** [comment]
This is now fixed thanks to your PR 👍
