### ISSUE TITLE
unexpected results when defining create_* in postgres

### ISSUE THREAD

**Issue by lifeiscontent** [graphile/graphile-engine#313]
using this example

```
echo "create table foo (id serial primary key, t text); create function create_foo(t text) returns foo as $\$ insert into foo(t) values(t) returning * $\$ language sql volatile;" | psql -X1 override_create
postgraphile -c override_create
```

`create_foo` expects this signature `create_foo(foo foo)` when being called from graphile instead of `create_foo(t text)` since I'm not omitting the create action on the table, and the type signatures don't match, this should probably warn the user or throw.

**Comment by benjie** [comment]
I've confirmed that the user is warned with an error message, and I've enhanced the error message to mention the `@omit create` smart comment.

Default:

![screenshot 2018-10-15 15 42 26](https://user-images.githubusercontent.com/129910/46958133-01924a80-d091-11e8-8584-954ed6ca7631.png)

With `DEBUG="graphile-build:warn"` envvar set:

![screenshot 2018-10-15 15 42 06](https://user-images.githubusercontent.com/129910/46958157-1242c080-d091-11e8-9793-3714743f2aef.png)
