### ISSUE TITLE
add data to context in hook

### ISSUE THREAD

**Issue by bejito** [graphile/graphile-engine#329]
Hello,

I am building a js plugin in which I extend a type with a few fields that do some http calls.
Each of the new fields resolvers is going to start by doing some common logic: deserializing a protobuf  that is in DB.
My issue is that I would like to do that deserialization only once, before the execution of any of the resolvers, and put the deserialized object in the context. The deserializatiomm itself can be complex and need external resources.

I looked at hooks for that:
- `GraphQLObjectType` might a good candidate, but I did not find a place where to put a piece of code to be executed for each object before going to any of the fields resolver.
- `GraphQLObjectType:fields` allows to add fields to the GQL type. The only place there I could add code that would be executed for each object is in the added fields resolvers, but I want the deserialization to be done whatsoever.
- `GraphQLObjectType:fields:field` is at field level, so already too low.

Is there way to do what I want to do ? Am I missing something ?

Thanks !

**Comment by benjie** [comment]
Hey @bejito; one simple way to approach this is with memoization: have them all call a function that does the work once and then re-uses the result for future calls. You'll want to use an LRU cache or similar.

Failing that; you need to find a way to make it work with how GraphQL works: each resolver is passed the parent object, args, context and resolve info. The idea is you do things based on the parent object. The parent object is what's resolved from the field. You could use the parent object as a cache (ick - mutating is bad!), or better, you could compute the relevant data as part of the parent object resolving and then the child fields can just use that. To make this more efficient you can use a Graphile Engine data loader to register the fields interest in having this entity precomputed, and only precompute it if that data was generated. Explaining how to do that is quite complex; I highly recommend the memoization route if you can go that way as the core of Graphile Engine is not deeply documented yet.

**Comment by bejito** [comment]
Thanks for you fast answer as always.

I had a solution working with the memoization but I was not totally satisfied with it as it seemed more like a patch than a real solution...

I am not sure I can add it to the parent resolving because my type can be at the root of the query. 

I'll go with memoization for now 👍

**Comment by benjie** [comment]
I think memoization is the best approach. You can put something on context to store the memoization to so it’ll be properly GC’d using additionalGraphQLContextFromRequest
