### ISSUE TITLE
Feature request: add option to sort NULLs last

### ISSUE THREAD

**Issue by wanradt** [graphile/graphile-engine#331]
Hi!

As Postgres by default sorts NULLs first while using descending sort, so does postgraphile. But in many/most situations is desired behaviour to put NULLS LAST.

For now there is no configuration option in postgraphile to trigger such behaviour.

TIA,

Gunnar

**Comment by benjie** [comment]
We just merged this in #332 👍 

We're not currently exposing this with a top-level flag, so to use it you need to use `graphileBuildOptions`; e.g.:

```js
app.use(postgraphile(DATABASE_URL, SCHEMA, {
  graphileBuildOptions: { orderByNullsLast: true }
}));
````

**Comment by christian-predebon** [comment]
Hi, I cannot find anything related to the flag `orderByNullsLast` in the docs. Is this flag still used and if so why can't I find it inside the type `PostGraphileOptions`?

**Comment by benjie** [comment]
Please see the example in the comment above yours - it lives within the graphileBuildOptions

**Comment by christian-predebon** [comment]
Oh right, I read it wrong. Thanks!

**Comment by JohnMusleh** [comment]
is there a way to define this for a single query and not on this level ? 

assume I want to use 2 different behaviors in different queries

**Comment by benjie** [comment]
Each enum value used for ordering can override the nulls first/last; but that's on an enum-value basis, not a field basis. You can also add your own orders that can specify nulls behaviour via [makeAddPgTableOrderByPlugin](https://www.graphile.org/postgraphile/make-add-pg-table-order-by-plugin/)

**Comment by JohnMusleh** [comment]
Thanks @benjie , which enum value are you talking about ?
can you give an example to better understand ?

**Comment by benjie** [comment]
The enum values that an `orderBy` argument uses. Here's where we add enum values for each column:

https://github.com/graphile/graphile-engine/blob/ff52f00751a1eb09e391a0ec6319815875de470a/packages/graphile-build-pg/src/plugins/PgOrderAllColumnsPlugin.js#L38

That tuple has two entries, you can add a third as `true` or `false` to force `NULLS FIRST` or `NULLS LAST` (I don't remember which way round it is though, sorry!).

**Comment by barbalex** [comment]
Sorry but after trying it out I haven't succeeded so asking: How do I achieve to sort with nulls first?

- is there a `orderByNullsFirst` option?
- would it be `orderByNullsLast: false`?

No matter what I do nulls seem to end up last.

Edit: So I saw in the code that it should be `orderByNullsLast: false`. Need to find out why that isn't working for me.

**Comment by benjie** [comment]
@barbalex Have you definitely put it inside `graphileBuildOptions` inside the PostGraphile options? I.e. it's a level deeper than you might expect.

**Comment by barbalex** [comment]
@benjie My bad. I suck at docker. Had to rebuild the local container. Works fine now. Thanks!

**Comment by rishabgupta-reeldata** [comment]
@benjie we are running [Postgraphile in Docker](https://www.graphile.org/postgraphile/running-postgraphile-in-docker/), so will only have access to the command line options.
Is there any way, we can specify this option from the command line?

**Comment by benjie** [comment]
Yes, add a postgraphilerc file to your docker container and configure it there.
