### ISSUE TITLE
Add `@deprecated` support to functions

### ISSUE THREAD

**Issue by benjie** [graphile/graphile-engine#336]
I think literally deleting this one line of code will work:

https://github.com/graphile/graphile-engine/blob/61957931d236b78c0c8791420d052ae8af22aecf/packages/graphile-build-pg/src/plugins/PgColumnDeprecationPlugin.js#L17

Would make the plugin a misnomer though.

**Comment by mattbretl** [comment]
For query procedures, `pgIntrospection` is undefined, so it still exits early because of L16. `pgFieldIntrospection` holds the introspected proc. Does that make sense?

**Comment by mattbretl** [comment]
I think it does. Just had to wrap my head around it.

**Comment by benjie** [comment]
Yeah, this leaks the evolution of the system a little too much 😳 I think it’s fine though; pgIntrospection is basically the Type, whereas pgFieldIntrospection is the field. But I have a vague feeling it works a little different for the root collections? Or maybe I fixed that... I don’t recall 😅
