### ISSUE TITLE
Check edge-case issue on adding a table with 100% `@omit filter`-ed columns

### ISSUE THREAD

**Issue by benjie** [graphile/graphile-engine#345]
```sql
create table p.omitted (
  id serial primary key
);

comment on column p.omitted.id is '@omit filter';
```

Should be handled by this:

https://github.com/graphile/graphile-engine/blob/61957931d236b78c0c8791420d052ae8af22aecf/packages/graphile-build-pg/src/plugins/PgConnectionArgCondition.js#L73

But apparently isn't because this doesn't return early?

https://github.com/graphile/graphile-engine/blob/61957931d236b78c0c8791420d052ae8af22aecf/packages/graphile-build-pg/src/plugins/PgConnectionArgCondition.js#L115-L120

**Comment by mattbretl** [comment]
For reference, the error is:
```
Error: Input Object type OmittedCondition must define one or more fields.
    at assertValidSchema (/home/matt/.npm/_npx/8684/lib/node_modules/postgraphile/node_modules/graphql/type/validate.js:82:11)
    at Object.validate (/home/matt/.npm/_npx/8684/lib/node_modules/postgraphile/node_modules/graphql/validation/validate.js:58:35)
    at parseQuery (/home/matt/.npm/_npx/8684/lib/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:219:48)
```

BUT, I just noticed that this only happens with 4.0.1. It works just fine in 4.1.0-rc.1.

With both 4.0.1 and 4.1.0-rc.1, `TableConditionType` was `null`, so the hook function was returning early (as it should have). But in 4.0.1, it seems the *Condition type was still being registered behind the scenes somewhere.

**Comment by benjie** [comment]
4.0.1 doesn’t pass true to newWithHooks 👍
