### ISSUE TITLE
error: operator is not unique: smallint[] @> smallint[] when `intarray` extension is installed

### ISSUE THREAD

**Issue by patsimon** [graphile/graphile-engine#372]
I'm submitting a ... 

* [ x] bug report

PostGraphile version: 4.0.1

Minimal SQL file that can be loaded into a clean database:

```sql
sorry.. the sql I have to create the schema is not minimal
```

Steps to reproduce:

When I run the following command on the command line... the servers starts up fine

`postgraphile -c postgres://username:password@pellefant.db.elephantsql.com:5432/dbname -a -j -o`

When I run the exact same command from within an npm start script in my package.json file - it falls over with the below exception

```
PostGraphile v4.2.0 server listening on port 5000 🚀

  ‣ GraphQL API:         http://localhost:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://localhost:5000/graphiql (enhance with '--enhance-graphiql')
  ‣ Postgres connection: postgres://username:[SECRET]@pellefant.db.elephantsql.com/dbname
  ‣ Postgres schema(s):  public
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Join Centre for Effective Altruism in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

A fatal error occurred when building the initial schema, so the process will now exit. Error details:

error: operator is not unique: smallint[] @> smallint[]
    at Connection.parseE (/Users/simoin/workspace/tenderpro/tenderpro_graphql_server/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/Users/simoin/workspace/tenderpro/tenderpro_graphql_server/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/Users/simoin/workspace/tenderpro/tenderpro_graphql_server/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

The end goal here is to run a graphine server in EC2 and using an npm script appears to be the easier way to do this.

The odd thing is, if I connect to my localhost, it all works via CLI and the npm start script....

**Comment by benjie** [comment]
Transferred to graphile-engine repo.

**Comment by patsimon** [comment]
> You’re running 4.2.0 via the npm script; my guess is you have 4.2.0 installed locally but 4.0.1 globally, hence the different behaviour. What version of postgres are you running? This looks like it might be an introspection query issue.

Thanks for the reply and fix. I'll check it out. FYI - postgres version is 9.5.2

**Comment by tyvdh** [comment]
Is there a way to test this? Just ran into this error my self and would love a way to test the fix by using the most up to date version of the graphile engine

**Comment by patsimon** [comment]
Not an expert in NPM modules, but I think you'd have to replace the version of graph-engine in your local node_modules with the master branch that has the fix.

This or wait until a newer version drops onto https://www.npmjs.com/package/postgraphile

**Comment by tyvdh** [comment]
Can confirm the latest version of postgraphile fixes this issue for me

**Comment by benjie** [comment]
Awesome; thanks @tyvdh

**Comment by benjie** [comment]
(`postgraphile@next` for anyone watching)
