### ISSUE TITLE
interval[] column has String input type

### ISSUE THREAD

**Issue by mattbretl** [graphile/graphile-engine#390]
```sql
create table foo (
  id serial primary key,
  "int" int,
  "int_array" int[],
  "timestamptz" timestamptz,
  "timestamptz_array" timestamptz[],
  "interval" interval,
  "interval_array" interval[]
);
```

![image](https://user-images.githubusercontent.com/17815830/51996169-21b51080-24ac-11e9-8405-93c045368eae.png)

**Comment by benjie** [comment]
Is this a regression, or has it always been the case?

**Comment by mattbretl** [comment]
I presume it's always been the case. I just noticed it while writing some tests for the filter plugin. The same thing happens with arrays of range types.

**Comment by benjie** [comment]
I'm fixing this; but giving people a way to opt out of the fix. See: https://github.com/graphile/graphile-engine/pull/405
