### ISSUE TITLE
@collection simple/relay/both smart comments

### ISSUE THREAD

**Issue by mathroc** [graphile/graphile-engine#392]
I'm usually going for Relay-compatible connections but for a few cases where I know there will always be only a few results I'd like to be able to switch to simple collections instead

**Comment by mathroc** [comment]
for context, for nom I'm either staying with Relay-compatible connections or switching to postgres array for the most simple cases.

postgres array are great but when it's an array of a custom type, I can't reference other tables in one of the type field

**Comment by benjie** [comment]
100% agree; this is planned (and should be fairly easy) but it’s good to have community confirmation it’s desired!
