### ISSUE TITLE
unknown option `--live'

### ISSUE THREAD

**Issue by fineline** [graphile/graphile-engine#420]
Getting this error when I try to start postgraphile with the `--live` option as per the docs for the plugin `subscriptions-lds` to try Live Queries. My versions are:

postgraphile 4.3.3
@postgraphile/subscriptions-lds 4.4.0-alpha.0

I am launching postgraphile with:
postgraphile --cors --connection postgres://forum_example_postgraphile:*****@localhost:5432 --schema forum_example --default-role forum_example_anonymous --secret keyboard_kitten --token forum_example.jwt_token --live --append-plugins @graphile/subscriptions-lds

I followed the standard install instructions and got the basic tutorial working, now trying to get realtime data from Postgres. I'm guessing I may need to obtain a more recent postgraphile? If so, would be good to add instruction on the Live Query page to help newbies like me.

**Comment by benjie** [comment]
`--live` needs PostGraphile v4.4.0 which is currently in beta. Install with `yarn add postgraphile@next`

Release notes:

https://github.com/graphile/postgraphile/releases

**Comment by benjie** [comment]
Also use `yarn add @graphile/subscriptions-lds@next` too.

**Comment by fineline** [comment]
Thanks Benjie, I'll give it a go later.

**Comment by fineline** [comment]
Thanks Benjie, can confirm that changing to the `@next` versions fixed this, and I can now see that there is a message about this on the top of the live queries documentation:

>> This feature requires PostGraphile v4.4.0 or higher.
