### ISSUE TITLE
Ignore-indexes has no option to selectively enable unindexed fields.

### ISSUE THREAD

**Issue by MichaelHudgins** [graphile/graphile-engine#430]
PostGraphile's option to exclude filters, orderBy, and relations for unindexed fields has no ability to re-enable this functionality on a per table or column basis.    I would suggest possibly adding a smart comment to allow for these operations to be enabled on an as needed basis.

**Comment by benjie** [comment]
Definitely.

**Comment by benjie** [comment]
If someone wants to add this, it should be fairly straightforward, you need to check where `isIndexed` is set, and look for a smart comment (e.g. `attr.tags.isIndexed`) and allow that to set it to true also. It will need tests.

**Comment by benjie** [comment]
In V5, the `PgIndexBehaviorsPlugin` gives unindexed relations the `-list -connection -single -manyToMany` behavior. You can override it by explicitly [adding the behaviors](https://postgraphile.org/postgraphile/next/behavior) (e.g. `+connection`) on the constraint.
