### ISSUE TITLE
Schema generated by Function returning Table doesn't have totalCount and pageInfo

### ISSUE THREAD

**Issue by xialvjun** [graphile/graphile-engine#455]
**Function returning Table**:
![image](https://user-images.githubusercontent.com/4413712/56795926-1de32100-6844-11e9-85c7-4e8f1b2f1f43.png)

**Schema generated**:
![image](https://user-images.githubusercontent.com/4413712/56795996-40753a00-6844-11e9-9cdc-5cf7c29720cb.png)

**Comment by benjie** [comment]
This issue has been open for a long time and no-one else has show interest in it, so I'm going to close it.
