### ISSUE TITLE
Sorting on computed properties with custom types

### ISSUE THREAD

**Issue by frankdugan3** [graphile/graphile-engine#463]
This was first asked on Discord a couple weeks ago, just getting around to filing an issue now.

I have a computed property that returns a custom type, and I have a smart comment setting `@sortable`, but it doesn't seem to appear in the `orderBy` options. Is that not covered by default? If not, how would I go about a plugin for enabling that?

**Comment by benjie** [comment]
Composite types don’t really have a sensible order, so you cannot order by them. You could add another computed column that calls your current one and extracts one of its properties to order by. Writing a plugin is a bit more involved; you can take the built in computed column ordering plugin as a base, change it to add ordering by the attributes on composite types:

https://github.com/graphile/graphile-engine/blob/master/packages/graphile-build-pg/src/plugins/PgOrderComputedColumnsPlugin.js

**Comment by frankdugan3** [comment]
To clarify, the behavior I was expecting is similar to how https://github.com/graphile-contrib/pg-order-by-related works for relations: Create sort options for each field of the composite type. In my particular case, I'd want to be able to sort on each of the fields. Also, one of the reasons I made the type a composite is because the values of the fields are dependent on each other, so I wanted to optimize the computation since it does some expensive selects (5 fields, so 5x redundant).

**Comment by benjie** [comment]
The plugin approach should work for this (though it's a bit of effort). But if you're in a rush, the additional computed column _shouldn't_ cause performance issues - because the functions are "stable" they shouldn't be re-calculated unnecessarily, effectively they are memoized by PG automatically (and if they aren't, try increasing their `COST` parameter).

**Comment by frankdugan3** [comment]
Oh, that's interesting. So much to learn about Postgres!

Do you foresee this sort functionality being added to core or pg-order-by-related? I don't have a hard deadline on sorting this way, just need to figure out how I plan to implement it in the near future.

**Comment by benjie** [comment]
I think I'd do it in a separate plugin to start with; when proven and the kinks are worked out I'd look at adding it to core.

**Comment by benjie** [comment]
I'm going to close this as I don't intend to add it to core. An external plugin should be feasible though :+1:
