### ISSUE TITLE
Be able to drop the `List` on computed columns when using simpleCollections

### ISSUE THREAD

**Issue by charlescrain** [graphile/graphile-engine#469]
Given the provided table and computed column:

```sql
CREATE TABLE person 
  ( id          BIGSERIAL 
  , name        TEXT NOT NULL
  , created_at  TIMESTAMP WITH TIME ZONE DEFAULT now()
  , PRIMARY KEY (id)
  );

CREATE OR REPLACE FUNCTION person_tags(p person) 
  RETURNS SETOF TEXT AS $$
  SELECT * FROM unnest(ARRAY['tag1','tag2'])
$$ LANGUAGE SQL STABLE;

COMMENT ON FUNCTION person_tags IS E'@simpleCollections only\n@fieldName tags';
```
I assume the following would be a valid query

```graphql
{
  personById(id:1) {
    id
    name
    tags
  }
}
```
However, the `tags` field is invalid and is `tagsList`.

The behavior is defined at line
https://github.com/graphile/graphile-engine/blob/master/packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js#L637 

I suggest changing:

```javascript
return proc.tags.fieldName
              ? proc.tags.fieldName + "List"
              : this.camelCase(`${pseudoColumnName}-list`);
```

to

```javascript
return proc.tags.fieldName
              ? proc.tags.fieldName
              : this.camelCase(`${pseudoColumnName}-list`);
```

Not sure if this has repercussions beyond the name but would be nice to set the name of simpleCollections.

**Comment by charlescrain** [comment]
Upon further reflection, if `@simpleCollection both` were used, then there would be a collision with the the original.

**Comment by benjie** [comment]
Changing it to `tags.simpleFieldName ||` (or fieldNameSimple; I forget) like other inflectors would be good 👍
