### ISSUE TITLE
graphile-utils missing dependencies in package.json

### ISSUE THREAD

**Issue by bradleyayers** [graphile/graphile-engine#470]
I'm migrating my project to Yarn 2 and it enforces packages to only be able to import from modules that are declared dependencies. `graphile-utils` is missing some dependencies, namely `graphile-build` and `graphile-build-pg` which are used in at least `makeExtendSchemaPlugin`.

**Comment by benjie** [comment]
`makeExtendSchemaPlugin` doesn't seem to have dependencies on those things: https://unpkg.com/graphile-utils@4.4.0/node8plus/makeExtendSchemaPlugin.js

(Only the TypeScript does, but that's only for types)

**Comment by bradleyayers** [comment]
Ah yes the problems I get are from the TypeScript types with  `graphile-utils` being unable to access types from `graphile-build`. So the return type of `makeExtendSchemaPlugin` ends up being `any` because it can't access `Plugin` from `graphile-build`.

What I'm actually doing is a bit sneaky by doing `import { AugmentedGraphQLFieldResolver } from "graphile-utils/node8plus/makeExtendSchemaPlugin";` to poke inside and pull out `AugmentedGraphQLFieldResolver` which I use to write types for my plugin definition, e.g.:

```ts
interface RichTextPluginDefinition {
  typeDefs: DocumentNode;
  resolvers: {
    RichTextContentCommitEventSubscriptionPayload: {
      richTextContentCommit: ReplaceReturnType<
        AugmentedGraphQLFieldResolver<{ subject: string }, Context, graphql.CreateRichTextContentCommitTypeMutationVariables>,
        Promise<unknown>
      >;
    };
    CreateRichTextContentCommitPayload: {
      richTextContentCommit: ReplaceReturnType<
        AugmentedGraphQLFieldResolver<CreateRichTextContentCommitIntermediateResult, Context, never>,
        Promise<unknown> | null
      >;
      error: ReplaceReturnType<
        AugmentedGraphQLFieldResolver<CreateRichTextContentCommitIntermediateResult, Context, never>,
        CreateRichTextContentCommitIntermediateResult["error"]
      >;
    };
    CreateRichTextContentCommitErrorPayload: {
      message: ReplaceReturnType<
        AugmentedGraphQLFieldResolver<CreateRichTextContentCommitIntermediateErrorResult, Context, never>,
        string
      >;
      missedCommits: ReplaceReturnType<
        AugmentedGraphQLFieldResolver<CreateRichTextContentCommitIntermediateErrorResult, Context, never>,
        Promise<unknown[]>
      >;
    };
    Mutation: {
      createRichTextContentCommit: ReplaceReturnType<
        AugmentedGraphQLFieldResolver<never, Context, graphql.CreateRichTextContentCommitTypeMutationVariables>,
        Promise<CreateRichTextContentCommitIntermediateResult>
      >;
    };
  };
}

// …

makeExtendSchemaPlugin(({ pgSql: sql }): RichTextPluginDefinition => ({
  resolvers: {
    RichTextContentCommitEventSubscriptionPayload: {
      richTextContentCommit: async (event, _args, _context, { graphile: { selectGraphQLResultFromTable } }) => {
        // …
      },
    }
    // …
  }
})
```

Doing it this way means I can have all the resolver types of my plugin colocated which I find makes it easier to navigate. Though this is a bit of an aside from the issue of the `graphile-utils` dependencies as `makeExtendSchemaPlugin` is public API and it's still affected.

**Comment by benjie** [comment]
A pull request to resolve this would be welcome, but we have to be careful to not cause the situation where there ends up being loads of different copies of `graphile-build` and `graphile-build-pg` in the `node_modules` tree. We could do it via `peerDependencies` but that tends to cause users to get confused by "missing peer dependency" errors (even though the modules are present). You can probably resolve this by installing all the modules manually, but then it's a nightmare to keep up to date. Maybe we should list explicit deps even though they aren't, and even though this can cause cyclical dependencies.

**Comment by benjie** [comment]
https://github.com/graphile/graphile-engine/pull/477 makes it so `AugmentedGraphQLFieldResolver` is a root export of graphile-utils; it'll be going out with 4.4.1

**Comment by benjie** [comment]
I've also added `peerDependencies` but I don't expect it to fix your issue, more likely to make it clearer that your dependencies need to be in a specific hierarchy (i.e. you need to install them all as flat as possible). This may necessitate installing all the dependencies manually 🙄

**Comment by benjie** [comment]
I'm not sure what more we can do for this, so I'm going to close it for now.
