### ISSUE TITLE
Support for Federation

### ISSUE THREAD

**Issue by ebekebe** [graphile/graphile-engine#474]
Hi,

we are currently looking into [GraphQL Federation](https://www.apollographql.com/docs/apollo-server/federation/introduction/) and really like to use it with Graphile. I couldn't find anything in the docs, so could you help me with that. Is it something that needs to be part of Graphile or is it more likely something for a plugin.

Thanks
Ben

**Comment by benjie** [comment]
Hi @ebekebe; please see the discussion here:

https://github.com/graphile/postgraphile/issues/1094

A fair amount of it can be achieved via `makeExtendSchemaPlugin` I think.

(Closing as duplicate.)

**Comment by ebekebe** [comment]
@benjie Thanks for the pointer 😀
