### ISSUE TITLE
If all out params return null then graphile returns null record

### ISSUE THREAD

**Issue by testarossaaaaa** [graphile/graphile-engine#503]
I use postgraphile@4.4.3

If all out params of function return `null` values then PostGraphile returns `null` record and not `{ lastOffer: null, total: null }`

SQL function:
```sql
create or replace function pub.client_retention (
  in c pub.client,
  out last_offer timestamptz, out total float8
) as $$
  select
    (select created_at from pub.order o where o.client_id = c.id order by created_at limit 1),
    (select sum(value) from pub.transaction t where t.client_id = c.id);
$$ language sql stable;
```

What graphile returns:

![image](https://user-images.githubusercontent.com/4533828/63146803-dd7efd00-c004-11e9-995c-adfdec80db05.png)

What postgres returns:

![image](https://user-images.githubusercontent.com/4533828/63146814-e66fce80-c004-11e9-9161-749c82c80bbe.png)

**Comment by benjie** [comment]
It’s very hard to distinguish between an object with all null values and a null. “Is null” returns true for both. In some cases you can use “is not distinct from null” but doing so is more expensive. Do you distinguish between these two? If not you could wrap the resolvers that return this type and have them return an empty object if the result would have been null.

**Comment by testarossaaaaa** [comment]
Got it, I will just wrap it with `coalesce`, thanks for explanation.
