### ISSUE TITLE
Request: Access parent arguments from resolveInfo

### ISSUE THREAD

**Issue by michaelbridge** [graphile/graphile-engine#504]
Let's assume I want to stitch in a third-party API.  I've added `arg1` to `parentType` via a `GraphQLObjectType:fields:field:args` hook and subsequently used `makeExtendSchemaPlugin` to request data from the API.  A sample query is below.

```
{
    parentType(arg1: "something") {
        myField1
        myField2
        ...
    }
}
```

After quite a lot of inspecting, I've concluded there's no way to access `arg1` from within the resolvers for `myField1` and `myField2`.  You can imagine a case where the same `arg1` is required to resolve `myFieldX` fields, and indeed consistency in the value of `arg1` is highly desirable.

It would seem a major help to provide a path to `arg1` from within `resolveInfo`, or perhaps I missed something and this is already available?

**Comment by benjie** [comment]
This isn’t “the GraphQL way”. ResolveInfo actually comes from GraphQL.js; but I believe if you raise the issue there you’ll be told the same as what I’m about to tell you: to pass information like this down, you include it in your result from the parent resolver. Fields lower down do not (and should not) know of the “context” they were requested in, the only thing they know is the parent object. So if they need to know about arg1 then the resolver for `parentType` should include this in its returned value, which is fed as the first argument to the resolvers for `myField1` and `myField2`.

**Comment by benjie** [comment]
I’m not going to implement this as requested for the reasons above, so I’m going to close the issue, but please feel free to keep discussing it below.
