### ISSUE TITLE
backward relations should take "@omit many" on foreign table and constraints into account

### ISSUE THREAD

**Issue by ab-pm** [graphile/graphile-engine#505]
I want to omit some "many" fields on a table (or really, on the whole table).
Unfortunately, the `@omit many` smart comment only allows me to annotate the table with the foreign key constraint, dropping all its backward relations - instead of having me annotate the referenced table, on which the fields to be dropped are generated. I would enjoy having an `omit(foreignTable, "many")` check added to the line https://github.com/graphile/graphile-engine/blob/b6fbfb849ee50e29b6c53114cb159dc4f12ddd19/packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js#L242 but I guess that would be a backwards-incompatible change. So if that is not possible, I'd suggest allowing `many` also on the individual constraints or fields, i.e. at https://github.com/graphile/graphile-engine/blob/b6fbfb849ee50e29b6c53114cb159dc4f12ddd19/packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js#L69 https://github.com/graphile/graphile-engine/blob/b6fbfb849ee50e29b6c53114cb159dc4f12ddd19/packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js#L103

**Comment by benjie** [comment]
Changing line 69 to `if (omit(constraint, "read") || omit(constraint, "many"))` with the relevant tests would likely be accepted as a PR :+1:

Also apparently we don't have any examples in the docs for `many` so that'd be welcome too :+1:
