### ISSUE TITLE
@pgQuery should work with scalars

### ISSUE THREAD

**Issue by BowlingX** [graphile/graphile-engine#507]
It seems currently not possible to use `@pgQuery` to produce simple scalars like

```graphql
extend type Type {
   foo: [Int!] @pgQuery(
                source: ${embed(sql.fragment`table`)}
                withQueryBuilder: ${embed((queryBuilder, args) => {
                 // ...
          })})
 }
```
The embedded code is not exectued this way. If I use a complex `Type` or `[Type]` it works as expected.

**Comment by benjie** [comment]
Fixed in https://github.com/graphile/graphile-engine/pull/534
