### ISSUE TITLE
Add a `@hasDefault` smart comment to indicate a create mutation input field should be nullable

### ISSUE THREAD

**Issue by rudism** [graphile/graphile-engine#509]
The basic use case here is that I have a view constructed by joining a couple of tables. The primary key of the view is a multi-column key inherited from one of those tables. The underlying table has both columns of the key `NOT NULL`, but one of them has a `DEFAULT` value set.

```sql
create table entity_main (
  pk_a text not null,
  pk_b text not null default 'default',
  value_a text,
  primary key (pk_a, pk_b)
);

create table entity_extra (
  pk_a text not null,
  pk_b text not null,
  value_b text,
  primary key (pk_a, pk_b),
  foreign key (pk_a, pk_b) references entity_main (pk_a, pk_b)
);

create view entity as
select
  base.pk_a,
  base.pk_b,
  base.value_a,
  extra.value_b
from
  entity_main base
inner join
  entity_extra extra on base.pk_a = extra.pk_a and base.pk_b = extra.pk_b;

comment on view entity is '@primaryKey pk_a, pk_b';
```

In the generated `createEntityMain` mutation only `pkA` is required because `pkB` has the default value, however in the `createEntity` mutation for the view both `pkA` and `pkB` are required because it doesn't know about the default value in the underlying table. (This is assuming appropriate triggers have been defined to make the view insertable.)

Is there currently a way I can override the implied `@notNull` behavior on `pk_b` in the primary key for the view?

**Comment by benjie** [comment]
It'd be possible to do this with a plugin, but I couldn't write one off the top of my head. What smart comment do you think would make sense here, perhaps `@hasDefault`? This would be useful in other situations too, e.g. where a trigger is responsible for adding a default rather than the `DEFAULT` statement.

**Comment by rudism** [comment]
`@hasDefault` makes sense to me.

**Comment by ab-pm** [comment]
Does this really need a smart comment, couldn't we just take into account the default (from introspection)? It shouldn't be a breaking change to make this nullable.

**Comment by benjie** [comment]
It's _extremely_ difficult to introspect a view.

**Comment by ab-pm** [comment]
Oops, sorry, I missed that the issue is about views.

**Comment by benjie** [comment]
This issue is not a priority since there are a fair few workarounds (and I've not needed it on any of my projects); if you'd like to help out with a PR (or if you're a sponsor and you need this) let me know.

**Comment by bfelbo** [comment]
FYI the @hasDefault smart tag has just been released: https://github.com/graphile/postgraphile/releases/tag/v4.12.5
