### ISSUE TITLE
Support @deprecated on constraints

### ISSUE THREAD

**Issue by mattbretl** [graphile/graphile-engine#510]
PostGraphile currently only respects the `@deprecated` smart comment on table columns, not constraints.

Ref: https://github.com/graphile-contrib/pg-many-to-many/issues/11#issuecomment-518254772

**Comment by benjie** [comment]
Fixed in V5: https://github.com/graphile/crystal/blob/5358591b20d5cd40f887ba90c30e77f8b1504754/graphile-build/graphile-build-pg/src/plugins/PgRelationsPlugin.ts#L837-L839
