### ISSUE TITLE
What is postgraphile_meta?

### ISSUE THREAD

**Issue by ab-pm** [graphile/graphile-engine#513]
I'm still trying to get the test running. I was expecting not having to set up the wal2json for @graphile/lds when not developing with that, but then found out that the tests of `postgraphile-core` do still try to use it, namely `/integration/live/*`.
Then I did try to setup a docker container for an appropriately configured postgres, and did pass that as the `LDS_TEST_DATABASE_URL` - only to find out that the integration tests run against the normal `TEST_DATABASE_URL`.
Even after fixing that, I am still getting the following message in my database logs:
```
2019-08-28 12:33:57.755 GMT [72] ERROR:  relation "postgraphile_meta.logical_decoding_slots" does not exist at character 60
2019-08-28 12:33:57.755 GMT [72] STATEMENT:  
	          with deleted_slots as (
	            delete from postgraphile_meta.logical_decoding_slots
	            where last_checkin < now() - interval '1 hour'
	            returning *
	          )
	          select pg_catalog.pg_drop_replication_slot(slot_name)
	          from deleted_slots
	          where exists (
	            select 1
	            from pg_catalog.pg_replication_slots
	            where pg_replication_slots.slot_name = deleted_slots.slot_name
	          )
```
The query apparently comes from [here](https://github.com/graphile/graphile-engine/blob/90cb0063ba326655d597a7e7a793833f4ea21077/packages/lds/src/pg-logical-decoding.ts#L117). What is its purpose? Neither the `logical_decoding_slots` nor the whole `postgraphile_meta` schema do exist.

**Comment by benjie** [comment]
It’s harmless; ignore it 👍

**Comment by benjie** [comment]
It’s from when you run LDS in dedicated mode. Which I don’t think we actually have tests for currently.
