### ISSUE TITLE
Add a lint:fix command to autoformat all the code for code review

### ISSUE THREAD

**Issue by benjie** [graphile/graphile-engine#518]
E.g. #479

Also, make the errors on CI more obvious (maybe using @danger?) - and say how to fix them!

Also maybe use husky to force formatting before commit?

Also maybe split linting into it's own CI task.

**Comment by garcianavalon** [comment]
Benjie, as youprobably already know, [eslint](https://eslint.org/docs/user-guide/command-line-interface) can be run with a `--fix` option. It could be added as a previous step to the `yarn watch` script, what do you think? This way it would be automated transparently for the contributor

**Comment by benjie** [comment]
Yeah, :heart: `eslint --fix` - it's primarily the reason I moved to JS from CoffeeScript. And now @typescript-eslint exists we can even use it with TypeScript - I'm slowly moving everything over to pure ESLint again.

I don't quite follow your suggestion - doing it before `watch` would not affect the newly contributed code?

**Comment by garcianavalon** [comment]
Well, my suggestion is based on my experience working on graphile-core. I had always running `yarn watch` running on another shell tab to compile changes. If that command run eslint first and warned me about/fixed errors before compiling that would have been a useful solution.

**Comment by benjie** [comment]
So I'm thinking that you'd check out a branch (no issues, clean), start running `yarn watch` (no issues, clean), write your code (not prettified, problem, but not spotted) and then submit the PR, finally closing `yarn watch`. Since you start `yarn watch` at the beginning I'm not sure linting before it runs is going to solve the problem in general.
