### ISSUE TITLE
How to remove fields created by other plugins?

### ISSUE THREAD

**Issue by ab-pm** [graphile/graphile-engine#521]
I would like to drop all the "id" fields for which the `PgForwardRelationPlugin` did create a real field containing the type. My API users can query `related { id }` instead of `relatedId` to fetch the id. How to do this?

My specific questions are:
* I guess I cannot `delete` (or filter out) the field in the `GraphQLObjectType:fields` hook, since that hook runs before the fields are added?
* Can I write a `GraphQLObjectType:fields:field` hook that does `return null`? I assume yes, but haven't tried yet - this depends on how `GraphQLObjectType` handles its spec, right? And this pattern will work only for fields, not for the root GrapqhQL types?
* How to find the fields that I want to delete? I guess I will need to look at the `scope` (fields created by the <s>`PgTablesPlugin`</s> `PgColumnsPlugin`) and then replicate the logic from the `PgForwardRelationPlugin` to detect whether they have an associated constraint etc that led to the creation of a relation?

(I hope to put your answers in a documentation update pull request :-) )

**Comment by benjie** [comment]
See [removing things from the schema](https://www.graphile.org/postgraphile/extending-raw/#removing-things-from-the-schema) - so long as your plugin comes after the plugin that adds the fields it should work.

> Can I write a GraphQLObjectType:fields:field hook that does return null?

I actually don't know what that will do. I wouldn't recommend it.

---

I actually plan to add this feature to core (behind a flag) at some point before V5. If you fancied doing a PR to core with the relevant changes instead, that'd be great :pray:

**Comment by ab-pm** [comment]
Oops. I think I had read that part of the documentation in the past :-/

I guess I was a bit confused by the timing of the `fieldWithHooks`, somehow expecting it to run after the `GraphQLObjectType:fields` hook, but now I realise that it runs *during* the other hook, with "nested" `GraphQLObjectType:fields:field` hooks, and still before the `GraphQLObjectType:fields` callback of other plugins.

**Comment by ab-pm** [comment]
A hack I used now in a similar case is to add `omit` tags to the introspection results in the `build` hook, so that the other plugins do never create the respective field themselves: https://gist.github.com/ab-pm/0f0b021db2c541008875b581f91404ee#file-plugin-ts-L45

**Comment by benjie** [comment]
This is a solid pattern; we have an example of this sort of thing in the docs:

https://www.graphile.org/postgraphile/plugin-gallery/#Customisation__OmitMutationsByDefaultPlugin

**Comment by ab-pm** [comment]
Ah, that's good to know! Still feels a bit awkward and cumbersome:
* you need to figure out what kind of db elements to tag with `omit`, duplicating the selection logic of the plugin
* the `omit` tags are sometimes not specific enough. To make the `rowByUniqueConstraints` field vanish, you'd need to `@omit read` the table, the attributes, or the unique constraint (and you cannot even `@omit` only `read` by itself so you'd need to omit all) - but that would lead to them being ignored in other cases where you don't them to

So I'm really looking for this v5 feature still :-) Hooks have access to the `scope` from which the field was created, which is much better to filter for and act upon.

**Comment by benjie** [comment]
Yeah `@omit read` is complicated so I just blocked it up front with the intention to circle back. I've never had time to do so though :disappointed:
