### ISSUE TITLE
graphile-build-pg in watch mode detects a "schema change" on startup

### ISSUE THREAD

**Issue by ab-pm** [graphile/graphile-engine#550]
When I run PostGraphile in watch mode during development, it always builds the schema twice on startup. This is inconvenient when also running it from `nodemon` to watch code changes, which means that startup is frequent.

I believe this is caused by https://github.com/graphile/graphile-engine/blob/1689f6691a0716d41d256de3499c9da40407348f/packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js#L923-L924
(and I can resolve it by commenting out that line) but I am not certain what "on reconnect" means here (in which cases that would happen). Maybe moving this into the `_reconnect` method would be the solution?

**Comment by benjie** [comment]
This is currently necessary otherwise there is a race condition: if something changes between when we build the first schema and when we enable watch mode we might miss it. A better solution is to not trigger a rebuild if the introspection results don’t differ.

**Comment by ab-pm** [comment]
Would it be possible to not "build the first schema" at all (at least when some plugins did register a watcher), then start watching to have that trigger the first build after it is set up?

**Comment by benjie** [comment]
Hmmm actually we don’t do the initial build. You’re right I think this is a regression introduced when we added better support for the PostgreSQL server restarting. I shall look into it in a few weeks 👍
