### ISSUE TITLE
graphile-build should export more/better hook types

### ISSUE THREAD

**Issue by ab-pm** [graphile/graphile-engine#553]
I'm trying to write my first plugin and have difficulties with TypeScript. It complains a lot about not being able to derive types for all my functions within `fieldWithHooks`. I could provide a lot of them myself, but I'd rather type it as the [`FieldWithHooksFunction`](https://github.com/graphile/graphile-engine/blob/master/packages/graphile-build/src/makeNewBuild.js#L137-L141). Unfortunately that doesn't seem to be exported anywhere, and importing it like
https://github.com/graphile/graphile-engine/blob/1d589633698b4bdfb2923226a330b6345505dd77/packages/graphile-build-pg/src/plugins/makeProcField.js#L5

does not work.

The ideal solution of course would be to not have the [overly generic `Hook` types in `SchemaBuilder.d.ts`](https://github.com/graphile/graphile-engine/blob/be18000f92ddca2f9cecb7b641c6f33ee63adb0e/packages/graphile-build/src/SchemaBuilder.d.ts#L41-L61), but rather use the [`ContextGraphQLObjectTypeFields`](https://github.com/graphile/graphile-engine/blob/be18000f92ddca2f9cecb7b641c6f33ee63adb0e/packages/graphile-build/src/SchemaBuilder.d.ts#L41-L61) etc in the respective hooks. Those looks like Flow types though?

**Comment by benjie** [comment]
Graphile Engine is slowly migrating from Flow to TypeScript. It's a big undertaking so we're trying to automate it with work on [flow2typescript](https://github.com/benjie/flow2typescript).

Relevant issues:

- https://github.com/graphile/graphile-engine/pull/516
- https://github.com/graphile/graphile-engine/pull/370

Once we're converted to TypeScript, [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) will make working with/extending the API a joy.

If you want to enable me to spend more time on this work, please sponsor generously: https://github.com/sponsors/benjie

Closing in favour of #516

**Comment by ab-pm** [comment]
Ah, cool! I guess I could help with fixing the remaining TypeScript issues.

**Comment by benjie** [comment]
Helping spot and file the TypeScript issues in the automated conversion would be really helpful - and if you can fix them (or even reproduce them via the tests) in flow2typescript even better! I want to translate everything in one shot once all the pending PRs are merged (doing the conversion whilst PRs are still open would involve a lot of additional work bringing the PRs back up to date).
