### ISSUE TITLE
singleRelationByKeysBackwards inflector should singularise foreignFieldName tag

### ISSUE THREAD

**Issue by ab-pm** [graphile/graphile-engine#557]
The title says it all :-) The issue is about these lines:

https://github.com/graphile/graphile-engine/blob/be18000f92ddca2f9cecb7b641c6f33ee63adb0e/packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js#L665-L670

The `foreignFieldName` tag is usually plural (it's mostly used by `manyRelationByKeys[Simple]`), but I would expect a *singleRelation* inflector to return a singular name. I've already overwritten this for myself in a custom inflector, but I believe the change should be made in graphile-engine as well (also in the [pg-simplify-inflector](https://github.com/graphile/pg-simplify-inflector/blob/38a008a7db3d2a421d57ee6d6cc8291de1222d6f/index.js#L211-L212)). How much of a compatibility issue would you expect from this?

**Comment by benjie** [comment]
This would be a breaking change, and I don't think it's sufficiently troublesome to implement. (The workaround is to use `foreignSingleFieldName` instead, which was added as a backwards-compatible fix for this issue.)

This is my first #wontfix for a while!

**Comment by ab-pm** [comment]
OK, I understand.
