### ISSUE TITLE
makeExtendSchemaPlugin: cannot reference inputTypes from input type extensions

### ISSUE THREAD

**Issue by ab-pm** [graphile/graphile-engine#575]
I've got a `thing` table for which I want to create custom mutations, nested in the mutation inputs for the `container` type. I've disabled the default mutations, but the types should be generated nonetheless and I want to reuse (and mangle) them.

This works:
```
gql`
extend type Mutation {
    updateThing(id: Int!, input: ThingInput!): Bool
    #                            ^^^^^^^^^^ notice reference here
    updateContainer(id: Int!, input: ContainerPatch!): Bool
}
extend input ContainerPatch {
    scalar: Bool # no problem with this extension
}
`
```
This does not:
```
gql`
extend type Mutation {
    updateContainer(id: Int!, input: ContainerPatch!): Bool
}
extend input ContainerPatch {
    scalar: Bool
    thing: ThingInput
    things: [ThingInput!]
}
`
```
I'm getting an **`Error: Could not find type named 'ThingInput'.…`**. With `DEBUG=graphile-build:warn` enabled, this is the trace:
```
Error: Could not find type named 'ThingInput'.
at getType (/app/node_modules/graphile-utils/src/makeExtendSchemaPlugin.ts:498:13)
at /app/node_modules/graphile-utils/src/makeExtendSchemaPlugin.ts:974:22
at Array.reduce (<anonymous>)
at getInputFields (/app/node_modules/graphile-utils/src/makeExtendSchemaPlugin.ts:970:19)
at /app/node_modules/graphile-utils/src/makeExtendSchemaPlugin.ts:462:32
at Array.reduce (<anonymous>)
at /app/node_modules/graphile-utils/src/makeExtendSchemaPlugin.ts:457:11
at SchemaBuilder.hook [as applyHooks] (/app/node_modules/graphile-build/src/SchemaBuilder.js:394:20)
at applyHooks (/app/node_modules/graphile-build/src/makeNewBuild.js:762:40)
at resolveThunk (/app/node_modules/graphql/type/definition.js:438:40)
```
(It says the error is recoverable, goes on without the entire `ContainerPatch` type, and then fails to find that from the `Mutation` field).

I don't think I'm deep enough into the hook system to find out why the types are created/extended in the wrong order (or: not lazily enough) and fix this myself. I can supply a more complete example to reproduce if needed.

**Comment by benjie** [comment]
Unfortunately this is an architectural issue with v4; the types and fields should have been more `evented` where you register a name but don't actually create it until it's asked for. Unfortunately this wasn't the case; and this isn't generally a problem in the normal plugin system but `makeExtendSchemaPlugin` does a lot of `getTypeByName` which causes this problem to be surfaced.

It's possible to fix these issues in an ad-hoc way; but I'm not planning on fixing it properly until v5 because it cannot be done in a backwards-compatible way.

**Comment by ab-pm** [comment]
I had expected exactly this to happen: all the types get created and registered first, then afterwards their `fields` thunks are evaluated and can already fetch any type by name. I guess I'll do some more digging later.

**Comment by ab-pm** [comment]
Ah, found it: the `performNonEmptyFieldsCheck` option causes the thunk to be evaluated prematurely (explicitly calling `Self.getFields()` to check its `.length`). Tbh I'm not quite sure why this doesn't fail more often :-)

What is `performNonEmptyFieldsCheck` really needed for? Afaics it's only used for the `TableInputType` and the `TablePatchType`, nowhere else, and all it does in `newWithHooks` is to prevent registering the type, scope and generators by name. Dropping it completely fixes the issue for me.

**Comment by benjie** [comment]
It’s needed to determine which types have no fields, because a GraphQL schema cannot contain a type with no fields. I think it’s also used on Mutation and Subscription? Some users `@omit` every column and then wonder why errors are thrown, which is why the checks you mention are implemented.

**Comment by ab-pm** [comment]
But the schema wouldn't even contain the type if it isn't referenced anywhere, so just constructing it and then ignoring it should be fine. If the users did manage to create a schema that does contain the type (as result type of a field or something), they imo should get the appropriate error message "*no fields in type X*" instead of "*type X not found*".

But I can now see where you are coming from, the framework uses the existence of types as a signal in a few places, e.g. https://github.com/graphile/graphile-engine/blob/1d589633698b4bdfb2923226a330b6345505dd77/packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js#L66-L74

I would prefer doing the <s>`isEmptyType`</s> `hasNoFields` check only there, when it comes to creating the field that might reference it. Forcing the fields later during the `:fields` hook would solve my problem (although it could lead to a nasty recursion that where we need to prevent reentry).

Would you accept a PR that implements this, or are you trying to come up with a holistic solution for v5?

**Comment by benjie** [comment]
As far as I know, this issue cannot be solved in a backwards compatible way in the v4 branch, I've looked at doing it before. There's a lot of third-party plugins in the wild.

**Comment by ab-pm** [comment]
You mean third-party plugins using `performNonEmptyFieldsCheck`? Or third-party plugins relying on the non/existence of the type?

**Comment by benjie** [comment]
Both.

**Comment by benjie** [comment]
In V5, all types are registered ahead of time, and referencing a type is forbidden except in a callback, so this should theoretically not be able to be an issue any more.
