### ISSUE TITLE
"extendedErrors" exists in documentation, but not present PostGraphileCoreOptions interface

### ISSUE THREAD

**Issue by davoam** [graphile/graphile-engine#592]
`extendedErrors` exists in documentation in the description of `createPostGraphileSchema `, but not present `PostGraphileCoreOptions` [interface](https://github.com/graphile/graphile-engine/blob/e9f6038ccabb31a231b72e94a3d2dc020e73e96d/packages/postgraphile-core/src/index.ts#L55) 

There is the following error displayed in IDE:
`TS2345: Argument of type '{ appendPlugins: any[]; extendedErrors: string[]; }' is not assignable to parameter of type 'PostGraphileCoreOptions'.   Object literal may only specify known properties, and 'extendedErrors' does not exist in type 'PostGraphileCoreOptions'.`

code which cause TS complier error:
```js
 createPostGraphileSchema(rootPgPool, graphQlSchemaName,
    {
        appendPlugins: [ConnectionFilterPlugin],
        extendedErrors: ['hint', 'detail', 'errcode']
    })
```

**Comment by benjie** [comment]
That's a bug in the documentation; immediately above this line:

https://github.com/graphile/postgraphile/blob/0ad482d5f9c4e8314d86f0ffc9f12d9e320578b1/src/interfaces.ts#L138

there should be a comment `/* @middlewareOnly */`

Would you like to raise a PR?

(Extended errors are handled at the server level, outside of the GraphQL schema; createPostGraphileSchema only deals in the schema itself so cannot implement this.)

**Comment by davoam** [comment]
@benjie thanks for the answer! I planned to fix on weekend but it looks like you already have merged the fix, thanks again!
