### ISSUE TITLE
[graphile-utils] `OrderSpec` type in `makeAddPgTableOrderByPlugin` is too restrictive

### ISSUE THREAD

**Issue by keithlayne** [graphile/graphile-engine#593]
`OrderSpec` is defined [here](https://github.com/graphile/graphile-engine/blob/master/packages/graphile-utils/src/makeAddPgTableOrderByPlugin.ts#L5).

The [example](https://www.graphile.org/postgraphile/make-add-pg-table-order-by-plugin/#example) from the docs doesn't match this type - it uses a function type in the first element of that tuple:

```ts
(context: GenContext) => SQLQuery
```

(Not sure that `GenContext` is actually right there)

TS error:

```
error TS2345: Argument of type '({}: GenContext) => SQLQuery' is not assignable to parameter of type 'string | SQLRawNode | SQLValueNode | SQLIdentifierNode | SQLQuery'.
  Type '({}: GenContext) => SQLQuery' is missing the following properties from type 'SQLQuery': pop, push, concat, join, and 27 more.
```

**Comment by benjie** [comment]
V5 overhauls all this, but I _think_ it's fixed. Places to look:

- https://postgraphile.org/postgraphile/next/make-add-pg-table-order-by-plugin#example
- https://github.com/graphile/crystal/blob/5358591b20d5cd40f887ba90c30e77f8b1504754/graphile-build/graphile-utils/src/makeAddPgTableOrderByPlugin.ts
- https://github.com/graphile/crystal/blob/5358591b20d5cd40f887ba90c30e77f8b1504754/grafast/dataplan-pg/src/interfaces.ts#L330-L360
