### ISSUE TITLE
`Map`s should use `String` as key?

### ISSUE THREAD

**Issue by dotansimha** [graphile/graphile-engine#603]
I'm submitting a ... 

@benjie 

* [x] bug report

PostGraphile version: `4.5.5`

Steps to reproduce:

I'm trying to use the programmatic usage of this tool, in order to integrate it with other tool I'm building. 
It seems like some parts of the implementation (such as `fieldDataGeneratorsByFieldNameByType` map) is using the GraphQL object as key, which causes issues with other tools such as `graphql-tools` and `graphql-toolkit`.

Doing something like that will cause the graphile resolvers to throw errors: 

```js
const { mergeSchemas } = require('@graphql-toolkit/schema-merging');

async function test() {
  const schema = await createPostGraphileSchema(
    'postgres://postgres:docker@localhost/postgres',
    ['public']
  );

  // Now `modifiedSchema` no longer works, because the resolvers
  // execution will not build the correct query, return some empty
  // objects, and eventually fail on access to `undefined`. 
  const modifiedSchema = mergeSchemas({
    schemas: [schema]
  });
}
```

Current behavior:

Other tools might modify or extend the schema, and in order to manipulate an existing `GraphQLSchema` object, it sometimes requires to create a new GraphQL object type. This change causes issues when later using `fieldDataGeneratorsByFieldNameByType.get` because it looks by reference for the type - causing `undefined` result, and then the query builder is not complete (all fields are missing). 

Expected behavior:

It seems like it would be better to use `fieldDataGeneratorsByFieldNameByType` (also `fieldArgDataGeneratorsByFieldNameByType` and `scopeByType`?) as `Map<string, object>`, it will make sure to get the real type even if the GraphQL type has been declared again.

**Comment by benjie** [comment]
This is an interesting point; Graphile Engine isn't currently designed for the schema to be manipulated _after_ being built - it's designed for the changes to take place during the build before the types are fully constructed. In version 4 it's possible to add plugins that can change/replace the name of a type whilst it is being built, however now that the inflection system is so powerful I don't believe this should be required or supported in V5 - in fact I'm planning to ban changing a field or type name after creation.

I'm planning to get rid of `fieldDataGeneratorsByFieldNameByType` entirely in V5 and instead store this information onto the newly public `extensions` property on various GraphQL types which should allow for a more straight-forward and compelling way to manipulate these values. Would this work with the tooling you have in mind?

**Comment by benjie** [comment]
A workaround for now would be to add the new type to the map, something like `map.set(newType, map.get(oldType))`

**Comment by dotansimha** [comment]
Thank you @benjie ! 
Is there a way to access those maps after the schema is created with `createPostGraphileSchema`?

**Comment by benjie** [comment]
You can add a plugin to extract the build object, something like:

```js
function makeExtractBuildPlugin(callback) {
  return builder => {
    builder.on(‘finalize’, (schema, build) => {callback(build); return schema;});
  }
}
```

That’s got everything you need on it I think.

**Comment by dotansimha** [comment]
Awesome! Thank you @benjie 
I managed to get this working as I need (by changing those maps, as you suggested). I'm having some other stuff to fix now, but it's not related directly to this issue (it seems like something is wrong with the enum resolvers, because when I do not specify `orderBy` explicitly it fails on some undefined, because args in resolvers is `{ orderBy: [undefined] }`).

**Comment by benjie** [comment]
It might be better to delegate to a PostGraphile schema rather than modifying it directly. At Graphile we believe a GraphQL schema (and all it’s types/fields) should be immutable, which is why we do all customisation before the constructors are called rather than modifying the constructed objects afterwards.

**Comment by benjie** [comment]
This is solved in V5 because rather than using external Maps we just store the relevant details into the `extensions` of the relevant field/type/etc. This is enabled by the new [Grafast engine](https://grafast.org).
