### ISSUE TITLE
Overriding gplType had no effect on custom mutation 

### ISSUE THREAD

**Issue by younes200** [graphile/graphile-engine#621]
Hi,
I'm using the the `GraphQLInputObjectType:fields:field` build hook to override a mutation args input type. 
The example that illustrate the problem, it basically override the `LocationInput` with custom `LocationTypeInput`

The schema result keep getting `LocationInput` despite the override.

I'm doing something wrong ?

```js
 builder.hook(
    "GraphQLInputObjectType:fields:field",
    (field, build, context) => {
      const { getTypeByName } = build;
      const {
        scope: { pgFieldIntrospection: attr },
      } = context;

      if (!attr || attr.kind !== "attribute") {
        return field;
      }

      // override based on attr type name but works too with field.gqlType
      if (attr.type.name != "location") {
        return field;
      }
      // LocationTypeInput is defined in other plugin
      const gqlType = getTypeByName("LocationTypeInput");
      if (!gqlType) {
        return field;
      }
      // trace here shows thee LocationTypeInput
      // console.log(gqlType) 
      return {
        ...field,
        type: gqlType,
      };
    }
  );
```

```graphql
input AddressMutationInput {
  location: LocationInput!
}
```

The SQL mutation : 

```sql
CREATE OR REPLACE FUNCTION  public.create_address(
	location public.location)
    RETURNS boolean
    LANGUAGE 'plpgsql'
    VOLATILE STRICT SECURITY DEFINER 
AS 
$BODY$
declare
begin
	##
end;
$BODY$;
```

Thank you.

**Comment by benjie** [comment]
In this case `attr.type.name` will be null since it's a nullable type. You can use `build.graphql.getNamedType(attr.type)` to get the named type, and then compare it's name, but don't forget to wrap the resulting type back up again. See the GraphQL documentation: https://graphql.org/graphql-js/type/

**Comment by younes200** [comment]
Thanks @benjie for the clarification. Much appreciated
