### ISSUE TITLE
TypeScript error on fieldsByTypeName of parseResolveInfo

### ISSUE THREAD

**Issue by dandv** [graphile/graphile-engine#622]
```ts
const fieldsRequested = parseResolveInfo(resolveInfo)
if (fieldsRequested.fieldsByTypeName.foo) ...
```

> TS2339: Property 'fieldsByTypeName' does not exist on type 'void | ResolveTree | FieldsByTypeName'.

At runtime, `fieldsRequested.fieldsByTypeName` evaluates correctly.

**Comment by benjie** [comment]
TypeScript's right, `void` has no fields. You need to do a truthy-check because `parseResolveInfo` may return null/void.
