### ISSUE TITLE
[graphql-parse-resolve-info] Missing documentation for ParseOptions passed to parseResolveInfo

### ISSUE THREAD

**Issue by glen-84** [graphile/graphile-engine#627]
The [README.md](https://github.com/graphile/graphile-engine/blob/7f0225e7bb69bbf3c135cdf1c5c155d92e916a71/packages/graphql-parse-resolve-info/README.md#parseresolveinforesolveinfo) file is missing information regarding the `ParseOptions` argument.

**Comment by benjie** [comment]
Correct; those are undocumented and unsupported options, use at your own risk - changes to them would not elicit a semver major change (though I don't have any planned).

**Comment by glen-84** [comment]
But this is part of the public interface, and if I'm not mistaken the options can affect the return type?

It seems strange not to document some of the arguments to an exported function.
