### ISSUE TITLE
[BUG] subscription not emit on DELETE operation

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [graphile/graphile-engine#643]
there is no issue template..... what do you think I should do?
Then a request from me: make an issue template BEFORE you close the issues without template...

![image](https://user-images.githubusercontent.com/69426460/91063556-d4246980-e636-11ea-8c8f-86409ba30326.png)

**Comment by benjie** [comment]
Ah; I missed this was against the Graphile Engine repo. Please follow the PostGraphile template and file a minimal reproduction. A title is not enough... There is no reason why a subscription should fire on a DELETE operation, subscriptions don't do anything unless you tell them to. Your question lacks context/details.

https://github.com/graphile/postgraphile/issues/new
