### ISSUE TITLE
`makeExtendSchemaPlugin` resolver doesn't recognize `nodeId`.

### ISSUE THREAD

**Issue by craigfay** [graphile/graphile-engine#646]
I've extended the schema using [`makeExtendSchemaPlugin`](https://www.graphile.org/postgraphile/make-extend-schema-plugin/), to introduce a custom resolver `createToken`, to replace the default `createToken` resolver, which I've omitted using [smart tags](https://www.graphile.org/postgraphile/smart-tags/):

```javascript
/*
 * Add types and a resolver to create a Token that has it's
 * `value` field automatically generated.
 */
export const withTokenCreation = makeExtendSchemaPlugin(build => {
  return {
    typeDefs: gql`
      input CreateTokenInput {
        title: String!
        description: String!
        adminId: Int
      }
      type CreateTokenPayload {
        token: Token,
      }
      extend type Mutation {
        createToken(input: CreateTokenInput!): CreateTokenPayload
      }
    `,
    resolvers: {
      Mutation: {
        createToken: async (parent, args, context, info) => {

          // inserting the new `token` record with knex.
          const [newToken] = await database('tokens').insert({
            "title": args.input.title,   
            "description": args.input.description,   
            "value": await token.create(),
            "admin_id": args.input.adminId,
          }).returning('*')

          // this `nodeId` appears valid, and is not null, but requesting
          // it causes errors
          newToken.nodeId = build.getNodeIdForTypeAndIdentifiers(
            build.getTypeByName('Token'),
            newToken.id,
          );

          console.log({ newToken })

          return {
            token: {
              ...newToken,
            },
          };

        }
      }
    },
  };
});
```

The plugin appears to work as expected, but we can't query for `nodeId`:

```graphql
# Graphql Request
mutation createToken {
  createToken(input: {title: "Example Token", description: "Just a test"}) {
    token {
      id
      # removing the next line will eliminate graphql errors
      nodeId
      title
      description
      value
      adminId
      createdAt
      updatedAt
    }
  }
}

```

Here's our output:

```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Token.nodeId.",
      "locations": [
        {
          "line": 63,
          "column": 7
        }
      ],
      "path": [
        "createToken",
        "token",
        "nodeId"
      ]
    }
  ],
  "data": {
    "createToken": {
      "token": null
    }
  }
```

The value of `console.log({ newToken })`:

```javascript
{
  newToken: {
    id: 20,
    title: 'Example Token',
    description: 'Just a test',
    value: '421641d43267a85f09e349f131c39e82e761c412323502e3aa8960a7587c2748',
    adminId: null,
    createdAt: 2020-09-03T01:28:23.129Z,
    updatedAt: 2020-09-03T01:28:23.129Z,
    // The nodeId exists, and is not null!
    nodeId: 'WyJ0b2tlbnMiLDIwXQ=='
  }
}
```

Here's a snippet of the GraphiQL docs for `Token`:
<img width="437" alt="Screen Shot 2020-09-02 at 9 14 52 PM" src="https://user-images.githubusercontent.com/31521775/92063722-7217e280-ed61-11ea-93c8-46d8093d38a6.png">

Conclusion: `nodeId` is present on the resolver's return value, but cannot be included in the query return value. I'm hopeful that this is just ignorance on my part, but I haven't been able to find any usage examples or docs that speak to this use case. Thanks in advance!

**Comment by craigfay** [comment]
I've roughly solved my own use case using [makeWrapResolverPlugin](https://www.graphile.org/postgraphile/make-wrap-resolvers-plugin/) and [makeChangeNullabilityPlugin](https://www.graphile.org/postgraphile/make-change-nullability-plugin/), which seems to be the mainline approach to these types of problems.

```javascript

/**
 * When a requester wants to create a token, generate the token's
 * `value` field, instead of letting the requester choose.
 */
export const generatingTokenValues = makeWrapResolversPlugin({
  Mutation: {
    createToken: async (resolver, user, args, context, _resolveInfo) => {
      args.input.token.value = token.create();
      return resolver();
    },
    updateToken: async (resolver, user, args, context, _resolveInfo) => {
      args.input.patch.value = token.create();
      return resolver();
    }
  }
});


/**
 * Don't force the requester to specify a `value` field when they're
 * creating a new token.
 */
export const withNullableTokenValues = makeChangeNullabilityPlugin({
  TokenInput: {
    value: true,
  },
});
```

Ideally, the `value` field wouldn't just be nullable, but excluded from the `TokenInput` object entirely.

I'm still curious if there's a concise way to accomplish this, and what might account for the original issue.

**Comment by benjie** [comment]
I’m afraid you’re effectively “hacking” PostGraphile with your approach here, which is why nodeId isn’t working. If Token had any relations or computed column functions, those would not work either. Instead, after inserting the token, you should use “selectGraphQLResultsFromTable” and @pgField to retrieve the row in a way PostGraphile can understand.

Please see this example: https://www.graphile.org/postgraphile/make-extend-schema-plugin/#mutation-example
