### ISSUE TITLE
Permission denied error not propagated to graphql result for tableByNodeId()

### ISSUE THREAD

**Issue by MarkASwanson** [graphile/graphile-engine#649]
### Summary
I've set GRANT permission in the database such that
```graphql
query {
  inquiry(id: 1) {
    id
  }
}
```
returns
```
{
  ...
  "message": "permission denied for table inquiry",
  ...
}
```
when no one is logged in (which is what i want).

---

However, the query
```graphql
query {
  inquiryByNodeId(nodeId: "WyJpbnF1aXJpZXMiLDFd") {
     id
  }
}
```
returns
```json
{
  "data": {
    "inquiryByNodeId": null
  }
}
```
I would have expected it to return the same error response as above.

Interestingly, if I enable explain, it **does** return the error response that I expect.

Is there something else I should do to get consistent permission errors for the auto generated ByNodeId queries?

---

### Additional context

I'm using [@graphile-contrib/pg-simplify-inflector](https://github.com/graphile/pg-simplify-inflector) which is why postgraphile is creating the inquiryByNodeId() graphql query.

This is my postgraphile config:
```js
{
  appendPlugins: [PgSimplifyInflectorPlugin],
  pgDefaultRole: 'starter_project_anonymous',
  jwtPgTypeIdentifier: 'starter_project.jwt_token',
  jwtSecret: process.env.JWT_SECRET,
  subscriptions: true,
  retryOnInitFail: true,
  dynamicJson: true,
  setofFunctionsContainNulls: false,
  ignoreRBAC: false,
  ignoreIndexes: false,
  graphiql: true,
  enhanceGraphiql: true,
  allowExplain: true,
  extendedErrors: ['hint', 'detail', 'errcode'],
  exportGqlSchemaPath: "build/schema.graphql",
  watchPg: true,
  ownerConnectionString: process.env.OWNER_DATABASE_URL,
  showErrorStack: 'json',
  enableQueryBatching: true,
  disableQueryLog: true,
  legacyRelations: 'omit',
}
```

**Comment by benjie** [comment]
It was a deliberate choice to swallow errors from the Node interface because the errors could reveal implementation details that the schema might not want to reveal, e.g. by passing specifically crafted values into the node ID. (This isn't an issue for the built in Nodes from PostgreSQL tables, but could be an issue for custom nodes the user might add via plugins.)

I'm happy with the status quo on this, effectively it's saying "there is no node with that identifier that you can see" which is accurate; like seeing a 404 when you try and view a private GitHub repo incognito, rather than a 403 explaining that it exists but you're not allowed to see it.

**Comment by MarkASwanson** [comment]
Alright that makes sense.

In that case, is there a good way to know that has happened when using postgraphile as a library?  I'm encountering the error ```current transaction is aborted, commands ignored until end of transaction block``` when trying to execute further queries in the same transaction (currently only doing this in testing, maybe I will never encounter a non-testing use case).

**Comment by benjie** [comment]
There's not really a good way to work around that with the architecture of v4, all the root level fields are run in parallel so you can't wrap them in savepoints (unlike mutations). I handle this by either allowing select or not to all PostGraphile roles, and using RLS to control which rows are visible. i.e. I'd permit select on your table and just have that the select always returns blank if you're not logged in. You can see this approach in action in Graphile Starter.

**Comment by MarkASwanson** [comment]
Ah ok.  I'm using RLS, but then denying selects on whole tables for certain roles.  I'll change to your suggested approach.  Thank you for the quick reply!
