### ISSUE TITLE
Improve context of connection errors.

### ISSUE THREAD

**Issue by purge** [graphile/graphile-engine#650]
### Feature description

When initially connecting errors are next to useless for debugging purposes:

```
A serious error occurred when building the initial schema. We'll try again in 100ms. Error details:

error: permission denied for schema app_public
[snipped useless stacktrace for pg-protocol]

```

This turned out to be due to graphile-engine requiring more permissions when connecting as an unprivileged user after adding enum tables.

Showing the query that caused the error would make this far easier to debug.

### Motivating example

I had to interrupt @benjie to work this out :)

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [ ] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [x] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
Good spot; what do you think about this for an improved error message? https://github.com/graphile/graphile-engine/pull/651

**Comment by purge** [comment]
LGTM 👍
