### ISSUE TITLE
Simple subscriptions missing relatedNode/relatedNodeId fields

### ISSUE THREAD

**Issue by younes200** [graphile/graphile-engine#697]
### Steps to reproduce
According the [documentation](https://www.graphile.org/postgraphile/subscriptions/#using) enabling `simpleSubscriptions: true` should expose `ListenPayload` with `relatedNode` and `relatedNodeId`.

### Expected results

```
type ListenPayload {
  query: Query
  relatedNode: Node
  relatedNodeId: ID
}

type Subscription {
  listen(topic: String!): ListenPayload!
}
```

### Actual results

```
type ListenPayload {
  query: Query
}

type Subscription {
  listen(topic: String!): ListenPayload!
}
```

### Additional context

Using last release of https://github.com/graphile/starter with simpleSubscriptions enabled results ListenPayload  with only `query`

**Comment by benjie** [comment]
Graphile Starter does not implement the Node interface (it explicitly skips the Node plugin) so you won't get the node fields added as there's no way to use them. If you want them, tell Starter not to exclude the Node plugin.

**Comment by younes200** [comment]
Thanks @benjie for the reply. Is there a reason why it’s omitted in starter template ?

**Comment by benjie** [comment]
Because I wanted a lean/small API and didn’t need it.

**Comment by younes200** [comment]
Thank you @benjie for you kindly feedback 👍🏼
