### ISSUE TITLE
Is it possible to use a different column from the primary key as a nodeId?

### ISSUE THREAD

**Issue by tiago-loureiro** [graphile/graphile-engine#698]
In order to avoid leaking my primary key to the outside world, I'd like to use a different column as the source for `nodeId`. For instance, given the following table:

```
create table orders
(
    id serial not null constraint orders_pk primary key,
    external_id uuid default uuid_generate_v4() not null,
    description text
);

create unique index orders_external_id_uindex
    on orders (external_id);
```

I'd like to use the `external_id` column to compute our `nodeId` instead of using my primary key. Two questions arise from this:

Questions:
1. Is this possible? Perhaps modifying the [node plugin](https://github.com/graphile/graphile-engine/blob/v4/packages/graphile-build/src/plugins/NodePlugin.js) ? I wasn't able to figure out if that's possible
2. Is this a good/bad idea, do you foresee any performance penalty (besides the extra space used for the index)? My understanding is that using `serial` as a primary key is beneficial for joining tables, etc. which is why I was wondering if this would be a smart approach?

**Comment by benjie** [comment]
If you don't want to expose your primary key, you should use a substitute primary key instead (e.g. a UUID) and make your current primary key into a unique key. We use the primary key in all sorts of places (e.g. cursors, node id, order always adds PK to the end for uniqueness, ...), so removing it is not supported.

Another alternative would be to use views/functions to reference your data and only expose those.

**Comment by RoryKelly** [comment]
@benjie To jump on the tail end of this conversation. Because `NodeId` is a base64 of primary key + table name

**Comment by RoryKelly** [comment]
@benjie I have the same problem^. Because NodeId is a reversible base64 of `primary key:table` it leaks primary key and table name.

I'm not sure I understand your suggestion. 
- I understand how to  use views/functions to reference your data.

- I don't understand `you should use a substitute primary key instead (e.g. a UUID) and make your current primary key into a unique key.`. Do you mean just use a UUID as a primary key? Doesn't this mean that the Node Id will still leak a primary key?

**Comment by benjie** [comment]
> Do you mean just use a UUID as a primary key?

Yes.

> Doesn't this mean that the Node Id will still leak a primary key?

Yes. This is by design; the node ID has to be reversable otherwise the `node(id: ID!)` resolver won't be able to reverse it.

---

Summary: if there's something secret about your primary key use a value that isn't secret as the primary key instead.
