### ISSUE TITLE
What happened to `createPostGraphileSchema` with `PgCatalog`?

### ISSUE THREAD

**Issue by benny-medflyt** [graphile/graphile-engine#718]
The documentation here: <https://www.graphile.org/postgraphile/usage-schema/#api-createpostgraphileschemapgconfig-schemaname-options>

It says that for the second argument, `pgSchema`:

> `schemaName`: A string which specifies the PostgreSQL schema that PostGraphile will use to create a GraphQL schema. The default schema is the `public` schema. May be an array for multiple schemas. **For users who want to run the Postgres introspection query ahead of time, you may also pass in a `PgCatalog` instance directly.**

I've emphasized the second part.

The code for this seems to have come from this pull request: https://github.com/graphile/postgraphile/pull/306/files

Notice that the type for the second parameter of `createPostGraphQLSchema` has `PgCatalog` added:

```typescript
schemaOrCatalog: string | Array<string> | PgCatalog = 'public'
```

But when I look at the latest code: <https://github.com/graphile/graphile-engine/blob/9d6c29e3505844ca64020fb6850093a7678a0fa4/packages/postgraphile-core/src/index.ts#L441>

it is reverted back to:

```typescript
schemas: Array<string> | string
```

In fact, I can't find the term `PgCatalog` anywhere in postgraphile source code.

How can I initialize postgraphile without doing live database introspection, and instead use a pre-computed catalog?

Thank you

**Comment by benjie** [comment]
Wow that's a throwback! That's an API from v3 (I think) that's no longer present in v4 and apparently the documentation was never updated (now fixed). It's not possible to support that interface in a stable way as we change the introspection query over time and in fact it can change based on what options you pass, and sometimes we also do follow-up introspection (e.g. for enum tables).

Instead you should use the (superior) `writeCache` / `readCache` functionality; for an example see this repo: https://github.com/graphile/postgraphile-lambda-example
