### ISSUE TITLE
Inline or require watch-fixtures.sql

### ISSUE THREAD

**Issue by marton78** [graphile/graphile-engine#721]
### Feature description

It would be great if `watch-fixtures.sql` could be converted to a `.js` file consisting only of one string literal, which could then be `require`d in `PgIntrospectionPlugin.js` instead of reading it with `await readFile(...)`.

### Motivaton

Currently, when building Postgraphile with [esbuild](https://esbuild.github.io/) and copying the resulting (huge) js file into a Docker container, everything works perfectly, only this file is missing. As a workaround, the file can be copied into `../../res/watch-fixtures.sql` but it would be lovely to remove this wart and thereby fully support bundling with esbuild.

### Breaking changes

None.

### Supporting development

I:

- [x] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [x] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
Have at it :+1:  Please note that the original file should continue to exist as it is used in at least my flows (e.g. I sometimes drop the watch schema, do a pg_dump, and then restore the watch schema using the bundled file), so you'd need to add a build script to convert it to JS as a build artifact (or vice versa)

**Comment by benjie** [comment]
Incidentally you should check out the webpack config we use for lambda; in particular these defines may reduce the size of your bundle:

https://github.com/graphile/postgraphile-lambda-example/blob/6a4a10c0d68714192aa3a881d8896d7e62593f8d/webpack.config.js#L19-L26

**Comment by benjie** [comment]
watchFixtures is a TS file in V5: https://github.com/graphile/crystal/blob/main/graphile-build/graphile-build-pg/src/watchFixtures.ts
