### ISSUE TITLE
Expected Identifier errors in IE11

### ISSUE THREAD

**Issue by amyngu** [graphile/graphile-engine#728]
### Summary

I am using parseResolveInfo for my app, and have found that when running on IE11 there are expected Identifier errors throwing at this line: https://github.com/graphile/graphile-engine/blob/1bc8cfefdab7a61fd7ad287bcdff66298352e308/packages/graphql-parse-resolve-info/src/index.ts#L58

Not sure if IE is a supported browser, if so, then this should be a bug, if it is not in the supported matrix please reply and let me know.

**Comment by benjie** [comment]
Hi @amyngu; these libraries are only intended to run on Node v8.6+, they were never intended for the browser. Nonetheless, you should be able to get support for that syntax by parsing the library with babel.

Cheers!
