### ISSUE TITLE
Generate more beautiful/readable sql

### ISSUE THREAD

**Issue by rattrayalex** [graphile/graphile-engine#734]
### Feature description

This is a nice-to-have idea for v5.

[This gist](https://gist.github.com/rattrayalex/ae39c2cf0356f1257ece4f3c4f6488cd) shows an example of a suggested reformatting, copied here:

<details>
<summary>For this GraphQL…</summary>

```gql
query MyQuery {
  films(
    filter: {and: [
      {title: {startsWith: "A"}}, 
      {releaseYear: {equalTo: 2006}}
    ]},
    first: 3
  ) {
    nodes {
      title
      releaseYear
      
      actors(first: 3) {
        nodes {
          actor {
            firstName
            lastName
          }
        }
      }
    }
  }
}
```

</details>

<details>
<summary>Instead of generating this SQL…</summary>

```sql
with __local_0__ as (
  select to_json(
    (
      json_build_object(
        'title'::text,
        (__local_1__."title"),
        'releaseYear'::text,
        (__local_1__."release_year"),
        '@actors'::text,
        (
          with __local_2__ as (
            select to_json(
              (
                json_build_object(
                  '@actor'::text,
                  (
                    select json_build_object(
                      'firstName'::text,
                      (__local_3__."first_name"),
                      'lastName'::text,
                      (__local_3__."last_name")
                    ) as object
                    from "public"."actor" as __local_3__
                    where (__local_4__."actor_id" = __local_3__."actor_id") and (TRUE) and (TRUE)
                  )
                )
              )
            ) as "@nodes"
            from (
              select __local_4__.*
              from "public"."film_actor" as __local_4__
              where (__local_4__."film_id" = __local_1__."film_id") and (TRUE) and (TRUE)
              order by __local_4__."actor_id" ASC,
              __local_4__."film_id" ASC
              limit 3
            ) __local_4__
          ),
          __local_5__ as (
            select json_agg(
              to_json(__local_2__)
            ) as data
            from __local_2__
          )
          select json_build_object(
            'data'::text,
            coalesce(
              (
                select __local_5__.data
                from __local_5__
              ),
              '[]'::json
            )
          )
        )
      )
    )
  ) as "@nodes"
  from (
    select __local_1__.*
    from "public"."film" as __local_1__
    where (
      (
        (
          (
            (
              __local_1__."title" LIKE $1
            )
          )
        )
        and (
          (
            (
              __local_1__."release_year" = $2
            )
          )
        )
      )
    ) and (TRUE) and (TRUE)
    order by __local_1__."film_id" ASC
    limit 3
  ) __local_1__
),
__local_6__ as (
  select json_agg(
    to_json(__local_0__)
  ) as data
  from __local_0__
)
select coalesce(
  (
    select __local_6__.data
    from __local_6__
  ),
  '[]'::json
) as "data"
```

</details>

<details>
<summary>Generate SQL like this…</summary>

```sql
select coalesce(json_agg(__film.data), '[]'::json) as "data" from (
  select json_build_object(
    '@nodes', json_build_object(
      'title', __film."title",
      'releaseYear', __film."release_year",
      '@actors', json_build_object(
        'data', (select coalesce(json_agg(__film_actor.data), '[]'::json) from (
          select json_build_object(
            '@nodes', json_build_object(
              '@actor', (
                select json_build_object(
                  'firstName', __actor."first_name",
                  'lastName', __actor."last_name"
                ) as object
                from "public"."actor" as __actor
                where __film_actor."actor_id" = __actor."actor_id"
              )
            )
          ) as data
          from "public"."film_actor" as __film_actor
          where __film_actor."film_id" = __film."film_id"
          order by __film_actor."actor_id" asc,
            __film_actor."film_id" asc
          limit 3
        ) __film_actor
      ))
    )
  ) as data
  from "public"."film" as __film
  where __film."title" like $1
    and __film."release_year" = $2
  order by __film."film_id" asc
  limit 3
) __film
```

</details>

Changes shown include:
1. Prefer aliases relevant to what is being represented, like `__film`, over anonymous ones like `__local_0__`.
2. Prefer subqueries to CTEs
3. Avoid extraneous parens, `::text` casts, and `and (TRUE)` clauses.
4. When using `json_build_object`, put both key and value on the same line.
5. Inline the coalesce/json_agg/from dance into a single line.

Of course, I know full well that beautiful code generation is much, much easier said than done, and some of these changes are easier and more useful than others. For example, using well-named aliases instead of anonymous ones would probably help the most; removing `::text` would help the least.

### Motivating example

Make it easier to understand and debug the queries generated by postgraphile.

Since postgraphile is designed to appeal to database-oriented individuals who like to deeply understand the queries they use, generating more readable sql might help them feel in control of the tool, rather than the other way around.

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [ ] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [x] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
As it happens we already have many of these changes in v5; enabled by the fact we’re no longer supporting Node v8 so we can use the symbol description 👍

**Comment by benjie** [comment]
There is a measurable performance difference between the compressed queries PostGraphile generates and formatted queries such as those you propose. We actually reformat the query with a regexp to make it easier for users to read:

https://github.com/graphile/graphile-engine/blob/v4/packages/graphile-build-pg/src/plugins/debugSql.js#L4

We _might_ implement a full SQL parser at some point to improve this formatting even further, but at the moment my plan is to punt this problem to prettier-plugin-pg which has its own issue tracker.

Avoiding the CTE is only appropriate in some cases; the moment you need to use pageInfo or similar you’ll need it again, there’s also consequences for the performance of the SQL.

In general the performance of the SQL will always be a higher priority than its beauty.

**Comment by benjie** [comment]
Note if you’re interested in just formatting the existing SQL the place to start would be the function linked above, and there’s no need to wait for V5 for that.

**Comment by rattrayalex** [comment]
Awesome, exciting!

I didn't know that about the "compressed" SQL (does that just mean whitespace removed?) but the approach of compressing over the wire and prettifying for human viewers sounds like a great one to me, for the most part (as long as there's some ability to understand what's happening in production). 

Given that, I definitely agree that prettier-plugin-pg is the right approach for much of this. I'd love to jam on that sometime soon if I can, I've been getting back into prettier development a bit recently…

Yeah, I assumed there were cases where the CTEs would actually be needed; my suggestion on that topic is to use subqueries in the other cases so you can more easily look at gql and sql side-by-side and quickly see what's doing what.

> In general the performance of the SQL will always be a higher priority than its beauty.

I definitely agree with this.

FWIW, for the query I was playing with, the rewritten version seemed to have a simpler plan with a slightly lower cost, and much less time spent on query planning:

**Original version (with CTEs) EXPLAIN ANALYZE output**

```
Result  (cost=103.50..103.51 rows=1 width=32) (actual time=0.532..0.535 rows=1 loops=1)
Planning Time: 3.290 ms
Execution Time: 0.711 ms
```

<details>
<summary>Full EXPLAIN ANALYZE output</summary>

```
Result  (cost=103.50..103.51 rows=1 width=32) (actual time=0.532..0.535 rows=1 loops=1)
  InitPlan 4 (returns $3)
    ->  Aggregate  (cost=103.48..103.49 rows=1 width=32) (actual time=0.529..0.532 rows=1 loops=1)
          ->  Limit  (cost=0.28..7.63 rows=3 width=167) (actual time=0.026..0.032 rows=3 loops=1)
                ->  Index Scan using film_pkey on film __local_1__  (cost=0.28..98.37 rows=40 width=167) (actual time=0.024..0.030 rows=3 loops=1)
                      Filter: ((title ~~ 'A%'::text) AND ((release_year)::integer = 2006))
          SubPlan 3
            ->  Result  (cost=31.92..31.93 rows=1 width=32) (actual time=0.154..0.155 rows=1 loops=3)
                  InitPlan 2 (returns $2)
                    ->  Aggregate  (cost=31.90..31.91 rows=1 width=32) (actual time=0.151..0.152 rows=1 loops=3)
                          ->  Limit  (cost=18.32..18.33 rows=3 width=16) (actual time=0.057..0.058 rows=3 loops=3)
                                ->  Sort  (cost=18.32..18.33 rows=5 width=16) (actual time=0.056..0.056 rows=3 loops=3)
                                      Sort Key: __local_4__.actor_id
                                      Sort Method: quicksort  Memory: 25kB
                                      ->  Bitmap Heap Scan on film_actor __local_4__  (cost=4.32..18.26 rows=5 width=16) (actual time=0.015..0.036 rows=6 loops=3)
                                            Recheck Cond: (film_id = __local_1__.film_id)
                                            Heap Blocks: exact=18
                                            ->  Bitmap Index Scan on idx_fk_film_id  (cost=0.00..4.32 rows=5 width=0) (actual time=0.011..0.011 rows=6 loops=3)
                                                  Index Cond: (film_id = __local_1__.film_id)
                          SubPlan 1
                            ->  Seq Scan on actor __local_3__  (cost=0.00..4.50 rows=1 width=32) (actual time=0.010..0.025 rows=1 loops=9)
                                  Filter: (__local_4__.actor_id = actor_id)
                                  Rows Removed by Filter: 199
Planning Time: 3.290 ms
Execution Time: 0.711 ms
```

</details>

**Rewritten version (with subqueries) EXPLAIN ANALYZE output**

```
Aggregate  (cost=103.48..103.49 rows=1 width=32) (actual time=0.424..0.427 rows=1 loops=1)
Planning Time: 0.526 ms
Execution Time: 0.563 ms
```

<details>
<summary>Full EXPLAIN ANALYZE output</summary>

```
Aggregate  (cost=103.48..103.49 rows=1 width=32) (actual time=0.424..0.427 rows=1 loops=1)
  ->  Limit  (cost=0.28..103.44 rows=3 width=36) (actual time=0.218..0.420 rows=3 loops=1)
        ->  Index Scan using film_pkey on film __film  (cost=0.28..1375.79 rows=40 width=36) (actual time=0.217..0.418 rows=3 loops=1)
              Filter: ((title ~~ 'A%'::text) AND ((release_year)::integer = 2006))
              SubPlan 2
                ->  Aggregate  (cost=31.92..31.93 rows=1 width=32) (actual time=0.122..0.123 rows=1 loops=3)
                      ->  Limit  (cost=18.32..31.88 rows=3 width=40) (actual time=0.067..0.118 rows=3 loops=3)
                            ->  Result  (cost=18.32..40.92 rows=5 width=40) (actual time=0.067..0.117 rows=3 loops=3)
                                  ->  Sort  (cost=18.32..18.33 rows=5 width=8) (actual time=0.027..0.028 rows=3 loops=3)
                                        Sort Key: __film_actor.actor_id
                                        Sort Method: quicksort  Memory: 25kB
                                        ->  Bitmap Heap Scan on film_actor __film_actor  (cost=4.32..18.26 rows=5 width=8) (actual time=0.012..0.018 rows=6 loops=3)
                                              Recheck Cond: (film_id = __film.film_id)
                                              Heap Blocks: exact=18
                                              ->  Bitmap Index Scan on idx_fk_film_id  (cost=0.00..4.32 rows=5 width=0) (actual time=0.008..0.008 rows=6 loops=3)
                                                    Index Cond: (film_id = __film.film_id)
                                  SubPlan 1
                                    ->  Seq Scan on actor __actor  (cost=0.00..4.50 rows=1 width=32) (actual time=0.011..0.025 rows=1 loops=9)
                                          Filter: (__film_actor.actor_id = actor_id)
                                          Rows Removed by Filter: 199
Planning Time: 0.526 ms
Execution Time: 0.563 ms
```

</details>

These were on the third successive run of the query, the planning time was a bit higher for the CTE version on first run. Over successive runs, as you might expect, execution time generally seemed equivalent for the two queries (0.5\~1ms), but planning time was consistently higher for the version with the CTE (1\~5ms vs 0.5\~1.5ms). 

My guess is that this is because the planner has to think about whether to inline the CTE as a subquery. That might be something graphile-engine could do more efficiently in this case.

Just to be explicit, I totally understand that this is ONE query from ONE toy database, and this is NOT a scientific benchmark, but I wanted to share.

**Comment by benjie** [comment]
Yeah; Postgres introduced inlining of CTEs which is really cool! Toggling between the two different query formats is definitely something that I considered, but I scoped it out to make maintenance easier - combinatorics would quickly expand the number of queries generated to a level that made testing and tracking down issues really cumbersome; given we prepare the statements and then reuse the query plan the additional couple milliseconds of planning time the first time we see the query didn't seem to be much of a concern.

Regarding prettier; head on over to this PR for the current latest version: https://github.com/benjie/prettier-plugin-pg/pull/11; **however** with the [latest advances to pg_query](https://pganalyze.com/blog/pg-query-2-0-postgres-query-parser) there's a strong chance we might move back to that parser. Lots of evaluation needed; if you want to take some of that on please feel free! I see prettier-plugin-pg as a hobby project and don't work on it very often (mostly I'm waiting for other people to build the parsing/etc bits I need so I can build it on top of them!)

> I didn't know that about the "compressed" SQL (does that just mean whitespace removed?)

Yes, we're careful how we write the `sql.fragment`s in the code so that they don't include unnecessary whitespace. It was mostly done in this commit: https://github.com/graphile/graphile-engine/commit/d57c18010a3eebf0ea9d63c9bb70637e34d67025

**Comment by rattrayalex** [comment]
Good point, cost of query planning would be immaterial when used with prepared statements. Silly me.

Yeah, sure would be ideal if `pg_query` can be used, it's great that it supports comments and so on now.

Thanks for sharing that commit, fun read. Surprised you didn't go for `.replace(/\n\s*/g, ' ')` or something on the constructed query but I guess that might slow things down… and maybe there's a chance that could happen inside of a string or something?

**Comment by benjie** [comment]
Yeah; there’s pg-minify that’d do that more safely but I’m trying to squeeze out every last bit of performance so better to just not introduce unnecessary whitespace in the first place.

**Comment by rattrayalex** [comment]
Ok cool - Given that better alias naming and other changes are coming in v5, CTE->Subquery when possible sounds like a wontfix, and whitespace/paren fixes best come from pg-plugin-prettier, I don't think this issue serves much purpose - closing. 

Thanks!
