### ISSUE TITLE
Transactional batch mutations with entities referencing multiple other (simultaneously) created entities

### ISSUE THREAD

**Issue by msand** [graphile/graphile-engine#746]
### Feature description

We have a use case where we would need to transactionally delete/create/update a potentially large number of entities of multiple different types, where some of the created/updated entities reference other entities created in the transaction.

### Motivating example

Our use case comes from a planning tool, where the users can create multiple scenarios with different modifications to the plans and compare the scenarios. The users can choose to commit to a scenario, at which point either all or none of the changes should be persisted. Any tool which can prepare changes to multiple kinds of entities, and where some of them have references to multiple other entities could have use for this pattern.

I've investigated the potential to implement this by combining:
postgraphile-plugin-nested-mutations
postgraphile-plugin-many-create-update-delete
postgraphile-plugin-atomic-mutations

But the nested mutations pattern doesn't allow for referencing multiple other entities

My current idea for what the graphql mutation would look like is something like this:

```graphql
mutation commitScenario(
  $deleteSchedules: [Int!]!
  $createSchedules: [CreateScheduleInput!]!
  $updateSchedules: [UpdateScheduleByIdInput!]!

  $deleteLocationVisits: [Int!]!
  $createLocationVisits: [CreateLocationVisitInput!]!
  $updateLocationVisits: [UpdateLocationVisitByIdInput!]!

  $deleteScheduleLocationVisits: [Int!]!
  $createScheduleLocationVisits: [CreateScheduleLocationVisitInput!]
  $updateScheduleLocationVisits: [UpdateScheduleLocationVisitByIdInput!]!
) {
  deleteScheduleLocationVisits(inputs: $deleteScheduleLocationVisits) {
    id
  }
  deleteSchedules(inputs: $deleteSchedules) {
    id
  }
  deleteLocationVisits(inputs: $deleteLocationVisits) {
    id
  }

  createSchedules(inputs: $createSchedules) {
    id
  }
  createLocationVisits(inputs: $createLocationVisits) {
    id
  }
  createScheduleLocationVisits(inputs: $createScheduleLocationVisits) {
    id
  }

  updateSchedules(inputs: $updateSchedules) {
    id
  }
  updateLocationVisits(inputs: $updateLocationVisits) {
    id
  }
  updateScheduleLocationVisits(inputs: $updateScheduleLocationVisits) {
    id
  }
}

```

In this case ScheduleLocationVisits references both Schedules and LocationVisits by id. 

The CreateScheduleLocationVisitInput and UpdateScheduleLocationVisitByIdInput types would instead of having Int type for the references, have a union type of `Int | { createSchedules: Int }` for the reference to schedules and `Int | { createLocationVisits: Int }` for the reference to LocationVisits. 

Such that in the case of the object type, e.g. { createSchedules: Int }, the Int would refer to the nth created schedule from this transaction.

### Supporting development

I:

- [ ] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [x] am willing to write a test-driven test suite for this feature (before it exists)
- [x] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

We're willing to enter into a support/consultancy contract and provide additional financing for the development of this feature.

**Comment by benjie** [comment]
> The CreateScheduleLocationVisitInput and UpdateScheduleLocationVisitByIdInput types would instead of having Int type for the references, have a union type of `Int | { createSchedules: Int }` for the reference to schedules and `Int | { createLocationVisits: Int }` for the reference to LocationVisits. 

Alas there is no such type in GraphQL. I am working towards creating a polymorphic input type in GraphQL: https://github.com/graphql/graphql-spec/pull/825

> My current idea for what the graphql mutation would look like is something like this:

GraphQL mutations are independent - so your first and third and fifth mutations could fail and your second and fourth mutations could succeed and this would be fine. For the atomicity that you require you need to perform all the actions through a single mutation field, e.g. by accepting a complex and nested input.

---

Are you sure you need a generic interface for this? Would a custom mutation be better suited?

**Comment by msand** [comment]
Thanks for the quick reply!

Oh didn't realize inputs have that kind of restriction, assumed it was possible as it's allowed for output types (or am I mistaken about that as well?).

I guess this means that I need to provide 2^2 different input and update types. Due to two references where each can be either pre-existing or created in this transaction, i.e. two states to the power of two references, 2^3 if there is three references etc. 

So in this case, four different types e.g.,
CreateScheduleLocationVisitInput (normal input where both references already exist)
CreateScheduleLocationVisitWithCreatedScheduleInput
CreateScheduleLocationVisitWithCreatedLocationVisitInput
CreateScheduleLocationVisitWithCreatedScheduleAndCreatedLocationVisitInput

Where plain Int is used for each reference, but the ones with CreatedEntityName suffix would refer to the nth created entity of that type. And symmetrically for updates. Seems this scales the types exponentially, and would get even worse in case e.g. ScheduleLocationVisit was referenced in a later entity.

Fortunately in our use case there is a small number of entity types having two references, and none have more than that. I hope your polymorphic input type gets accepted into the spec and supported soon.

For now I guess there's no other feasible approach than to create a custom mutation, I'm uncertain about the maturity of / how battle tested the:
postgraphile-plugin-nested-mutations
postgraphile-plugin-many-create-update-delete
postgraphile-plugin-atomic-mutations
plugins are.

**Comment by benjie** [comment]
> Oh didn't realize inputs have that kind of restriction, assumed it was possible as it's allowed for output types (or am I mistaken about that as well?).

You're mistaken there too I'm afraid; unions can only exist of object types - scalars cannot exist naked in a union.


> I hope your polymorphic input type gets accepted into the spec and supported soon.

You can emulate it now by just using a "wrapper" input type. You'll have to do the uniqueness validation yourself, but it's a pretty lightweight proposal.

**Comment by msand** [comment]
Oh yeah, confused it with the typescript types that get generated from our graphql schema, e.g.

```typescript
export type Scalars = {

/* ...snip */

  /** A floating point number that requires more precision than IEEE 754 binary 64 */
  BigFloat: string | number;

/* snip... */

};
```

Feel free to close this issue unless you wish to discuss this further / gather more feedback from others with similar interests.

**Comment by benjie** [comment]
`BigFloat` will always be a string :+1:

**Comment by msand** [comment]
Thanks for your suggestions here, in the end made a custom mutation and this kind of helper for the oneOf case:

```graphql
input CreatedOrExisting {
  created: Int
  existing: Int
}

type Ident {
  id: Int
}
```

```typescript
// Generated types
export type CreatedOrExisting = {
  created?: Maybe<Scalars['Int']>;
  existing?: Maybe<Scalars['Int']>;
};

export type Ident = {
  __typename?: 'Ident';
  id?: Maybe<Scalars['Int']>;
};

// Helpers
export function createdOrExisting(
  createdOrExistingValue: CreatedOrExisting,
  createdEntities?: Ident[] | undefined
): number {
  const { created, existing } = createdOrExistingValue;
  if (typeof existing === 'number') {
    return existing;
  }
  if (typeof created === 'number') {
    if (created < 0) {
      throw new Error('Referred to created entity, but using negative value');
    }
    if (!createdEntities) {
      throw new Error('Referred to created entity but none exist');
    }
    if (createdEntities.length <= created) {
      throw new Error(
        'Referred to created entity, but fewer created entities exist than reference requires'
      );
    }
    const id = createdEntities[created].id;
    if (typeof id !== 'number') {
      throw new Error(
        'Referred to created entity, but created id is not a number'
      );
    }
    return id;
  }
  throw new Error('Neither existing nor created entity referred to');
}

async function deleteEntities(
  pgClient: PoolClient,
  query: string,
  toDelete: Maybe<number[]> | undefined,
  errMsg: string
) {
  if (!toDelete || toDelete.length === 0) {
    return undefined;
  }
  const result = await pgClient.query(query, [toDelete]);
  const deleted = result.rows;
  if (deleted.length !== toDelete.length) {
    throw new Error(errMsg);
  }
  return deleted;
}

async function insertEntities<Entity>(
  pgClient: PoolClient,
  query: string,
  toCreate: Maybe<Entity[]> | undefined,
  errMsg: string
): Promise<Ident[] | undefined> {
  if (!toCreate || toCreate.length === 0) {
    return undefined;
  }
  const result = await pgClient.query(query, [JSON.stringify(toCreate)]);
  const created = result.rows;
  if (created.length !== toCreate.length) {
    throw new Error(errMsg);
  }
  return created;
}
```

With batch insertion queries generated by something like this:

```typescript
function generateQuery(build: Build, table_name: string) {
  const table = build.pgIntrospectionResultsByKind.type.find(
    ({ name }: any) => name === table_name
  );

  const attrs = table.class.attributes.filter(
    ({ tags }: any) => !tags.omit?.includes('create')
  );

  const transformNames: { [any: string]: string | undefined } = {
    end: '"end"',
  };
  
  return `INSERT INTO ${table_name} (${attrs
    .map(({ name }: any) => transformNames[name] || name)
    .join(', ')})
SELECT ${attrs
    .map(({ name }: any) => '"' + build.inflection.camelCase(name) + '"')
    .join(', ')}
FROM jsonb_to_recordset($1::jsonb) AS t (${attrs
    .map(
      ({ name, type }: any) =>
        '"' + build.inflection.camelCase(name) + '" ' + type.name
    )
    .join(', ')})
RETURNING id`;
}
```

Batch deletions:
```typescript
export const deleteSomethingQuery = `DELETE FROM something WHERE id = ANY($1) RETURNING id`;
```

And updates handled using the pattern shown here: https://www.graphile.org/postgraphile/usage-schema/#example

All done inside a single transaction. This pattern places some restrictions on the use, especially insertions don't set default values, as jsonb_to_recordset makes all missing values have null, but this is not a problem in our case, and the performance is very nice. Thanks again @benjie for all your great work on PostGraphile!

**Comment by benjie** [comment]
Excellent! Be careful of SQL injection here, but given you control all the names I imagine it won't be an issue? I'd generally feed it all through an escape function anyway; e.g.

```js
const escapeIdentifier = name => `"${name.replace(/"/g, '""')}"`;
```

**Comment by msand** [comment]
Yes, we're in control of all the names, additionally, we store the generated queries as text in version control and use the stored queries in the actual code. Such that we can review how they change over time, and adapt the code e.g. in case we would introduce some column / type which would require conversion. We need to adapt the graphql interface whenever we do that anyway. Could of course generate all of it dynamically, but this part of our system has barely been changing anymore and we expect it to be stable enough not to require much attention.
