### ISSUE TITLE
Error: Schema validation error: operation hooks were not added to the following fields: Mutation.

### ISSUE THREAD

**Issue by Knaackee** [graphile/graphile-engine#750]
I would like to wrap an existing mutation so that i can do something after the insert.
I followed the guide at: [makeWrapResolversPlugin (graphile-utils)](https://www.graphile.org/postgraphile/make-wrap-resolvers-plugin/#method-1-wrapping-individual-resolvers-of-known-fields)

I have a mutation called `createUser` and i can see and use it in graphiql. 

On startup, i get the following error.

> Error: Schema validation error: operation hooks were not added to the following fields: Mutation.createUser

```javascript
makeWrapResolversPlugin({
  Mutation: {
    async createUser(resolve, source, args, context, resolveInfo) {
      await resolve(source, args, context, resolveInfo);
      // do something
    },
  },
}),
```

Why is that? 

Thanks!

**Comment by benjie** [comment]
Looks like you're using the operation hooks plugin and there's some kind of ordering issue with the two plugins where operation hooks wraps the mutation before you then wrap it again. I've not seen this issue - maybe have operation hooks take the action you need rather than makeWrapResolversPlugin?

**Comment by Knaackee** [comment]
Hey @benjie 

thanks for your answer! Iam not using the hooks plugin. Iam not using any plugin for that. I do like in the docs and didnt find any mention of that plugin in the docs @ https://www.graphile.org/postgraphile/make-wrap-resolvers-plugin/#method-1-wrapping-individual-resolvers-of-known-fields

Did i miss something here ?

Thanks again!
