### ISSUE TITLE
`deletedUserId` is different from user `id`

### ISSUE THREAD

**Issue by nickkang1** [graphile/graphile-engine#763]
### Summary

When I use the built in delete mutation, there's a return field called `deleteUserId` that returns type `ID`. I think it should be identical to the User's `id` field.

When I base64 decode the two fields this is what I get:

```sql
CREATE TABLE users (
  user_id  bigint primary key
)
```

| Field Name    | Base64 Encoded       | Decoded               |
|---------------|----------------------|-----------------------|
| deletedUserId | WyJvZmZlcnMiLCI3Il0= | `"[\"users\",\"1\"]"` |
| id            | WyJvZmZlcnMiLDdd     | `"[\"users\",1]"`     |

It looks like `deletedUserId` is parsing the userId as a string while `id` is parsing the userId as a number.

Happy to provide more context.

I'm on `"postgraphile": "^4.12.0-alpha.0"`

**Comment by benjie** [comment]
This is fixed in V5 which handles NodeIDs in a new and more consistent way.
