### ISSUE TITLE
Hook into postgres introspection to throw on missing schema

### ISSUE THREAD

**Issue by csreid** [graphile/graphile-engine#767]
### Feature description

I see that there's an option to throw if the requested schema is missing in the database. I'd like to be able to hook into that to just kill the server if the schema is missing. I wouldn't be surprised if this is already somewhere, but I haven't found it, so maybe this is also a documentation request.

### Motivating example

While developing, my API server is always up before my migrations have run, which means the schema is never there on a fresh `docker compose up`, and that's a bit painful. I *could* use something like `wait-for-it.sh`, but that's crufty and a little hacky. I'd rather just fail fast and let docker just bring my API server up repeatedly until it doesn't crash.

### Supporting development

I [tick all that apply]:

- [x] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [x] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
I think it'd be better for you to just add a check before booting PostGraphile/the rest of your server:

```ts
const pg = require('pg');

const pgPool = new pg.Pool({connectionString});

const { rows } = await pgPool.query('select 1 from pg_namespace where nspname = $1', [mySchemaHere]);

if (rows.length === 0) {
  process.exit(1);
}

app.use(postgraphile(pgPool, [mySchemaHere], ...));

app.listen(...);
```

**Comment by csreid** [comment]
This would *work* but that also feels a little crufty to me, especially since postgraphile already knows enough about the problem to log a warning. And anyway, it feels like "you said to go use `schema_X` but that doesn't exist" is an error scenario that callers might want an option to handle.

Is there some design issue with letting raising an error there?

**Comment by benjie** [comment]
I don't see the value in adding a third way of handling this. The first way is the default - log a warning. The second is to use the option you mention `pgThrowOnMissingSchema` to throw an error. I don't see value in adding an explicit `process.exit` as a third option.

With the option you mentioned set the postgraphile server does exit by default; I'm assuming you've added `retryOnInitFail` or similar (because otherwise we wouldn't be having this conversation?) so you've explicitly opted to not have the process exit on failure, so adding an option that then overrides that to actually do exit is potentially confusing - even just documenting it is going to be challenging!

Here's a reproduction script of PostGraphile exiting when the schema is missing:

```bash
#!/usr/bin/env bash
set -e

# What DB are we messing with? (THIS DB WILL BE OVERWRITTEN!)
DATABASE="issue-767"
SCHEMA="app_public"

# Populate database
dropdb --if-exists "$DATABASE"
createdb "$DATABASE"
psql -X1v ON_ERROR_STOP=1 "$DATABASE" <<HERE
create schema something_else;

-- YOUR SQL HERE
HERE

# Install deps
yarn add --dev postgraphile @graphile-contrib/pg-simplify-inflector

cat > .postgraphilerc.js <<HERE
module.exports = {
  options: {
    graphileBuildOptions: {
      pgThrowOnMissingSchema: true
    }
  }
};
HERE

# Run PostGraphile
yarn postgraphile \
  --subscriptions \
  --watch \
  --dynamic-json \
  --no-setof-functions-contain-nulls \
  --no-ignore-rbac \
  --no-ignore-indexes \
  --show-error-stack=json \
  --extended-errors hint,detail,errcode \
  --append-plugins @graphile-contrib/pg-simplify-inflector \
  --graphiql "/" \
  --enhance-graphiql \
  --allow-explain \
  --enable-query-batching \
  --legacy-relations omit \
  --connection "$DATABASE" \
  --schema "$SCHEMA"

```

```
PostGraphile v4.12.5 server listening on port 5000 🚀

  ‣ GraphQL API:         http://localhost:5000/graphql (subscriptions enabled)
  ‣ GraphiQL GUI/IDE:    http://localhost:5000/
  ‣ Postgres connection: postgres:///issue-767 (watching)
  ‣ Postgres schema(s):  app_public
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Node.js version:     v16.13.0 on linux x64
  ‣ Join domonda in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

Error: You requested to use schema 'app_public'; however we couldn't find some of those! Missing schemas are: 'app_public'
    at introspect (/home/benjie/Dev/DELETEME/issue-767/node_modules/graphile-build-pg/node8plus/plugins/PgIntrospectionPlugin.js:549:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PgIntrospectionPlugin (/home/benjie/Dev/DELETEME/issue-767/node_modules/graphile-build-pg/node8plus/plugins/PgIntrospectionPlugin.js:686:39)
    at async getBuilder (/home/benjie/Dev/DELETEME/issue-767/node_modules/graphile-build/node8plus/index.js:169:5)
    at async Object.watchPostGraphileSchema (/home/benjie/Dev/DELETEME/issue-767/node_modules/postgraphile-core/node8plus/index.js:245:21)
    at async createGqlSchema (/home/benjie/Dev/DELETEME/issue-767/node_modules/postgraphile/build/postgraphile/postgraphile.js:114:21)
    at async Object.enhanceHttpServerWithWebSockets (/home/benjie/Dev/DELETEME/issue-767/node_modules/postgraphile/build/postgraphile/http/subscriptions.js:50:20)

error Command failed with exit code 34.
```

**Comment by csreid** [comment]
```
  graphileBuildOptions: {
    pgThrowOnMissingSchema: true
  }
```

hey hey, there's what I was after!

Seems like maybe my question wasn't clear from the beginning, my bad. I wasn't asking for a third option, I just wanted to be able to toggle that option to let it throw instead of logging the warning.

Is this `graphileBuildOptions` thing documented anywhere, and what's the vibe on getting similar behavior from the library? I see [this in the docs](https://www.graphile.org/postgraphile/usage-cli/)

>Please note that this interface is deprecated and will be removed in v5 (but its replacement hasn't been built yet...). You're encouraged to use PostGraphile as a library rather than using a .postgraphilerc.js.

so I'm assuming there's similar functionality for the library, but I can't find docs on it.

Again, happy to help however I can!

**Comment by benjie** [comment]
```js
postgraphile(DB_URL, SCHEMAS, {
  // ...
  graphileBuildOptions: {
    pgThrowOnMissingSchema: true
  }
});
```

PR to the docs welcome :+1:

**Comment by benjie** [comment]
In V5 you can hook into the `gather` phase to take custom actions.
