### ISSUE TITLE
A function returning a custom type is not sortable

### ISSUE THREAD

**Issue by madtibo** [graphile/graphile-engine#769]
### Summary

If a function is returning a setof that is a table, the sortable smart comment enables the orderBy option.  
If the function is returning a custom type, the sortable smart comment does not enable the orderBy option.

Is it normal? Is there a specific comment to add in the custom type to make it work?

### Additional context

Using :
* node": 14.16.0,
* graphile-build: 4.12.0,
* graphile-utils: 4.12.1,
* graphql-upload: 12.0.0,
* @graphile-contrib/pg-omit-archived: 2.1.0,
* @graphile-contrib/pg-order-by-related: 1.0.0-beta.6,
* @graphile-contrib/pg-simplify-inflector: 6.1.0,
* @graphile/pg-aggregates: 0.1.0,
* @graphile/postgis: 0.1.0,
* postgraphile: 4.12.3,
* postgraphile-plugin-connection-filter: 2.2.1,
* postgraphile-plugin-connection-filter-postgis: 1.0.0-alpha.6,
* postgraphile-plugin-fulltext-filter: spacefill/postgraphile-plugin-fulltext-filter#filter-plugin-v2-compat,
* postgraphile-plugin-upload-field: 1.0.0-alpha.10.

The `person_friends_table()` is sortable, the `person_friends_type()` is not.

```sql
drop schema if exists
  c
cascade;

create schema c;

create table public.person (
  id serial primary key,
  person_full_name varchar not null,
  about text,
  email text not null unique,
  created_at timestamp default current_timestamp
);

create type public.person_type AS (
  id int,
  person_full_name varchar,
  about text,
  email text,
  created_at timestamp
);

COMMENT ON TYPE public.person_type is
    E'@primaryKey id';

create function public.person_friends_table() returns setof public.person as $$ select friend.* from public.person as friend $$ language sql stable;
comment on function public.person_friends_table() is E'@name person_friends_table\n@sortable';

create function public.person_friends_type() returns setof public.person_type as $$ select friend.* from public.person as friend $$ language sql stable;
comment on function public.person_friends_type() is E'@name person_friends_type\n@sortable';
```

**Comment by benjie** [comment]
We don’t generate *OrderBy or *Condition for types, only tables.

**Comment by madtibo** [comment]
@benjie thank you for this information.

[The documentation](https://github.com/graphile/graphile.github.io/blob/develop/src/pages/postgraphile/smart-tags.md) tells that "table type" can use the `@sortable` tag. Maybe this could be reworded to:

```diff
 - Functions returning `SETOF` a table-like composite type (e.g. a table type,
-  view, materialized view, etc): adds the `orderBy` argument to this connection,
-  allowing to _sort_ the set by its columns/attributes.
+  view, materialized view, etc, but do not a custom type): adds the `orderBy`
+  argument to this connection, allowing to _sort_ the set by its
+  columns/attributes.
 - Computed column functions with no required parameters and returning a scalar
   or array: allows this function to be used as an order in the `orderBy`
   argument for the parent table, allowing to _sort_ the parent table _by_ this
```

**Comment by benjie** [comment]
Please send a PR :+1: "table-like" was mean to mean "you can pull data from it like you would a table" (which you cannot with a composite type).

By the way, you can totally work around this by defining your composite type as a table and just never storing anything to that table.

**Comment by madtibo** [comment]
Thanks for the tip, that is exactly what I am doing.
