### ISSUE TITLE
Asynchronous builder hooks

### ISSUE THREAD

**Issue by mgagliardo91** [graphile/graphile-engine#771]
I was digging around in the docs and couldn't find anything that stood out: Can builder/plugin hooks support asynchronous execution (returning promises?). The use case involves schema transformation based on external sources which I would like to execute at the time the schema is being rebuilt.

Thanks!

**Comment by benjie** [comment]
No; schema building is synchronous because it’s an API over GraphQL.js’ API which is also synchronous. Your plugins can do async things but they must complete them before the schema build triggers.
