### ISSUE TITLE
GraphQL v16

### ISSUE THREAD

**Issue by glen-84** [graphile/graphile-engine#773]
### Feature description

Support for GraphQL v16. I'm aware of the exploration in https://github.com/graphile/graphile-engine/pull/764, but I wanted to open this for tracking purposes.

I'm currently only using `graphql-parse-resolve-info`.

### Motivating example

Latest features, etc.

### Breaking changes

Dropping support for Node 8 and Node 10, but these are EOL anyway.

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [ ] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by machineghost** [comment]
This is blocking file uploads on Postgraphile.  When I try to install `graphql-upload` (as per the file upload example in Postgraphile) I get:

```
npm ERR! 
npm ERR! Conflicting peer dependency: graphql@16.7.1
npm ERR! node_modules/graphql
npm ERR!   peer graphql@"^16.3.0" from graphql-upload@16.0.2
npm ERR!   node_modules/graphql-upload
npm ERR!     graphql-upload@"*" from the root project
```

**Comment by benjie** [comment]
I personally am of the opinion that GraphQL is not a good fit for file uploads in general. That said, try using an older version of that module.

**Comment by machineghost** [comment]
>I personally am of the opinion that GraphQL is not a good fit for file uploads in general

I agree.

However, 95% of my API is non-file upload (and thus makes sense for Postgraphile), and all of my user/permission logic is baked-in to Postgres/Postgraphile ... so it just doesn't make sense to have a separate REST endpoint just for the file uploads.

>That said, try using an older version of that module.

Will do! Should I take this to mean Postgraphile won't be getting a new Graphql dependency anytime soon?

**Comment by machineghost** [comment]
P.S. For anyone else with the same issue, you have to go back to `graphql-upload` version 13.0.0 (the library's latest version is 16.0.02) to get the library to install with the current Postgraphile.

In other words:

    npm i graphql-upload@13.0.0

**Comment by benjie** [comment]
PostGraphile V5 is currently built around GraphQL v16. It’s possible we might go to v17 before release, depends on timing. No idea if it works with file uploads though since Grafast replaces the execution engine in GraphQL.

**Comment by benjie** [comment]
GraphQL v16 is used in V5.
