### ISSUE TITLE
[graphql-parse-resolve-info] Fix types or example

### ISSUE THREAD

**Issue by lorensr** [graphile/graphile-engine#783]
### Summary
Documentation says to do this:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/251288/161690457-77a7fd7f-8193-464d-b6a0-85a87e6136f6.png">

But when I do it, I get a TypeScript error:

<img width="1684" alt="image" src="https://user-images.githubusercontent.com/251288/161690608-ee20b516-147e-48ec-a7c4-a272ef483d35.png">

**Comment by benjie** [comment]
Put `as ResolveTree` after the error and it should go away.

**Comment by BlairCurrey** [comment]
Seeing the same.

text dump of error:

    Argument of type 'ResolveTree | FieldsByTypeName | null | undefined' is not assignable to parameter of type 'ResolveTree'.
      Type 'undefined' is not assignable to type 'ResolveTree'.

**Comment by benjie** [comment]
To be clear, the example code written in JavaScript is correct. If you want to use it with TypeScript then you need to either add the above type cast (`parsedResolvedInfoFragment as ResolveTree`) or do some other type narrowing behaviour. We could potentially change the signature of the function to something like:

```ts
export function parseResolveInfo(
  resolveInfo: GraphQLResolveInfo,
): ResolveTree | null | undefined;
export function parseResolveInfo(
  resolveInfo: GraphQLResolveInfo,
  options: ParseOptions
): ResolveTree | FieldsByTypeName | null | undefined;
export function parseResolveInfo(
  resolveInfo: GraphQLResolveInfo,
  options: ParseOptions = {}
): ResolveTree | FieldsByTypeName | null | undefined {
```

but overloaded functions in TypeScript have all sorts of issues that they can cause down the road so I'm not keen to do that, especially given all you need to do is add `as ResolveTree` if you know that's what it's going to be based on the options that you've passed.
