### ISSUE TITLE
[graphile-build]: Types for Build Don't Match Source

### ISSUE THREAD

**Issue by shellscape** [graphile/graphile-engine#802]
### Summary

The types for `Build` that are shipped in `SchemaBuilder.d.ts` don't match the types as declared in `SchemaBuilder.js`. 

### Steps to reproduce

We can look at the type for `Build` that is shipped in the `d.ts` file with the source:

`d.ts`:
https://github.com/graphile/graphile-engine/blob/1bc8cfefdab7a61fd7ad287bcdff66298352e308/packages/graphile-build/src/SchemaBuilder.d.ts#L42-L45

source:
https://github.com/graphile/graphile-engine/blob/1bc8cfefdab7a61fd7ad287bcdff66298352e308/packages/graphile-build/src/SchemaBuilder.js#L61-L65

`Build` is missing 99% of the relevant type information that has instead been replaced with an `any` index. 

### Expected results

I expected there to be a full typing of what was available on `Build`

### Actual results

Maintaining types is not easy, and I acknowledge that. But the way the types are shipped, it's _more_ problematic than not having any types, or relying on the community to maintain types. Using `any` so prolifically doesn't offer type hinting, direction, or documentation and I can't overstate how damaging that is to the developer experience. Instead, we're left to source dive and guess as to which types line up with the signatures we see in the documentation. If `flow` is the issue, we have tools for that: https://github.com/Khan/flow-to-ts.

### Possible Solution

Please ship some accurate typings, or place a call for help to the community (which I will gladly echo) on Twitter et al.

**Comment by benjie** [comment]
Unfortunately after a lot of work on this subject from a number of people it was deemed that adding this amount of types was deemed too much of a breaking change for V4 (it would have broken almost everyone's applications that were using TypeScript, and would have required significant migration effort). V5 is fully typed in TypeScript but isn't quite ready for prime time yet.

**Comment by benjie** [comment]
(Incidentally I wrote https://github.com/benjie/flow2typescript specifically for this purpose, poured many _many_ hours into this work. See https://github.com/graphile/graphile-engine/pull/573 and the related PRs for history.)

**Comment by shellscape** [comment]
Is there any chance of a supplementary types package? With no timeline for v5, we're putting a significant amount of time into source tracing due to a lack of meaningful types.

**Comment by benjie** [comment]
If you want to turn #573 into some supplementary types package, be my guest. Then you could do things like `const typedBuild = build as TypedBuild` or whatever. I'm not going to spend any time on it, I need to focus on getting V5 finished and released.
