### ISSUE TITLE
alias a column at mutation time only?

### ISSUE THREAD

**Issue by saranrapjs** [graphile/graphile-engine#834]
### Summary

I've been playing around with Postgraphile, and it's been really great! There are very few parts of it that aren't hackable, which allowed my team to do things that might be hard in another graphql/db framework.

One thing I was hoping to do was to change the naming of a GraphQL input that's produced from a column, so that it's different from the column in the context of a query. It seems like this might not be possible? [My read of the update/delete mutation plugin](https://github.com/graphile/graphile-engine/blob/v4/packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js#L114-L127) suggests that you can change the name using inflection (but this will change it for queries too), and there's maybe not a hook to be able to change the name (or add additional SQL to the executed query) for mutations like there sort of are for queries. But would be curious to know if I have that right!

**Comment by benjie** [comment]
Indeed, we just have the `column` inflector... PostGraphile has existed in one form or another for 7 years and I don't remember anyone ever asking for this before!

As it happens, this is already reasonably easy to do in PostGraphile V5 (which is undergoing the final stages of development and is sponsors only right now); you would remove the `create` and `update` behaviors from the column and then use `makeExtendSchemaPlugin` to add the input field (with a different name) and give it a plan that sets the relevant column value. There's no equivalent to this in V4, alas.

**Comment by benjie** [comment]
V5 is no longer sponsors-only; so I'm closing this.
