### ISSUE TITLE
pg-pubsub call to removeListener looks like it will not work

### ISSUE THREAD

**Issue by jcalfee** [graphile/graphile-engine#845]
This call to removeListener looks like it will not work.  Every call will create a new function so the client will not know which listener to remove.

https://github.com/graphile/graphile-engine/blob/v4/packages/pg-pubsub/src/index.ts
```js
const onClientError = client => err => {
  console.error('ddl:pubsub client error', err)
  releaseClient(client)
  if (!pgPool.ending) {
    setupClient()
  }
}

let listeningClient: PoolClient | null

function cleanClient(client: PoolClient) {
  client.removeListener("error", onClientError(client))
  // ...
```

**Comment by benjie** [comment]
I've no idea what you're looking at, but the file you've linked doesn't seem to contain that code; it doesn't contain `onClientError` nor `ddl:pubsub`. GitHub can't find a match for `onClientError` across the codebase:

https://github.com/search?q=repo%3Agraphile%2Fgraphile-engine%20onClientError&type=code

**Comment by jcalfee** [comment]
I apologize .. I copied file locally and started a new refactor from that and must have made the bug before I went to refactor.  Ok, glad there is no bug..

**Comment by benjie** [comment]
Lol ok 🤣

**Comment by jcalfee** [comment]
I based this on your code there.  I was looking for something based on the pool (like yours) but stand-alone and with some functions I can use to make an atomic cache (like exposing the keepAlive and after [un]listen and errors).  It is starting to work for me, but may still have bugs in it so I have ALPHA in the title.

https://gist.github.com/jcalfee/eb092f95571f9e3f1beec4dd2222463d
