### ISSUE TITLE
Defining two types with the same schema should be allowed

### ISSUE THREAD

**Issue by chrispytoes** [graphile/graphile-engine#857]
Defining two different types with different names but the same properties should be allowed and not throw an error on build. Apollo uses type names to differentiate between different caches. So if I'm forced to use the same type for two totally different records that just happen to look the same, Apollo will assume they're of the same collection and start getting them confused.

For example, my application has Statuses and Types. Both have just two properties, `id` and `name`, but they are two totally different tables. If I'm not allowed to define different types for each, then I'm forced to disable Apollo caching for that type entirely or else it thinks they're the same kind of record.

**Comment by benjie** [comment]
Yes, I agree, defining two different types that have the same properties should be allowed.

Since it is allowed, I will go ahead and close this issue.
