### ISSUE TITLE
Order by column on related table [plugin available]

### ISSUE THREAD

**Issue by mathroc** [graphile/graphile-engine#88]
I’ve tried to make a plugin to order by column on foreign table of a collection, I took inspiration from `PgOrderAllColumnsPlugin.js` however I don’t know how to go further, this is what I have:

```js

    const attrs = introspectionResultsByKind.attribute.filter(attr => attr.classId === table.id);

    const res = introspectionResultsByKind.constraint
      .filter(con => con.type === "f")
      .filter(con => con.classId === table.id)
      .map(con => ({con, foreignTable: introspectionResultsByKind.classById[con.foreignClassId]}))
      .map(({con, foreignTable}) => ({
        con,
        foreignTable,
        foreignAttrs: introspectionResultsByKind.attribute
          .filter(attr => attr.classId === foreignTable.id)
          .filter(attr => attr.type.type === "b")
          .filter(attr => attr.type.name !== "uuid")
      })).filter(({foreignAttrs}) => foreignAttrs.length > 0);

    return extend(values, res.reduce((memo, r) => {
      return r.foreignAttrs.reduce((memo, ra) => {
        [true, false].reduce((memo, dir) => {
          const ascFieldName = inflection.orderByEnum(
            [...r.con.keyAttributeNums.map(i => attrs.filter(a => a.num === i)[0].name), ra.name].join("-"),
            dir,
            table.name,
            table.namespaceName
          );
          console.log(table.name, ascFieldName);
          memo[ascFieldName] = {
            value: {
              alias: ascFieldName.toLowerCase(),
              specs: [["???", dir]]
            }
          };
          return memo;
        }, memo)
        return memo;
      }, memo)
    }, {}));
```

when I inspect the schema, I can see it adds the order bys I want. but I don’t know what to put instead of `"???"`. 

for starters I’d be happy if it works only when another part of the graphql query adds the "join" on the related table, but here I can’t yet know the subquery for that related table alias. I can see [here](https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js#L88) that I could put something else than a string but I can’t find example of that and can’t think of any pg-sql expr would be useful in my case

is this possible without patching `PgConnectionArgOrderBy.js` ?

(related: https://github.com/postgraphql/postgraphql/issues/119#issuecomment-324275857)

**Comment by benjie** [comment]
We don't currently use joins, we use subqueries (see #2 regarding using joins instead for some circumstances). Are you talking about a -to-one relation? i.e.

```sql
create table emails (
  id serial primary key,
  email_address text not null
);

create table users (
  id serial primary key,
  name text not null,
  email_id int not null references emails
);
```

and you want to do something like

```graphql
{
  allUsers(orderBy: EMAIL__EMAIL_ADDRESS) {
     edges { node { id name emailByEmailId { address } } } 
  }
}
```

?

**Comment by mathroc** [comment]
yes that’s this kind of relation and graphql I’d like to make. and if possible I’m trying to avoid duplicating the email_address field (on the graphql schema side). I could duplicate those fields in postgres and somehow filter them after #73 but then I’ll need to do this manually for each field I want and this seems to come with a high maintenance cost

I have not looked in detail what the generated query look like, with subqueries, if I was somehow able to figure out the corresponding table alias, would adding an order by on one of its field work?

**Comment by benjie** [comment]
You could do it with a subquery for now, which is not efficient but it'll let you use the functionality until #2 is solved. Equivalent of:


```sql
select * from users order by (select email_address from emails where id = users.email_id) asc;
```

So then your ??? would be a function returning the subquery above using the `pgSql` fragment builders. I can't remember what the function is passed, you may need to look at the other orderBy's, but ultimately you need a reference to `queryBuilder.getTableAlias()` to replace the `users` in `users.email_id` above.

**Comment by mathroc** [comment]
so I managed to build the subquery, but I don’t think I have access to the querybuilder here. the functon is called here : https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/QueryBuilder.js#L510 but it got no arguments. can I make a PR to add the querybuilder to the call ?

**Comment by benjie** [comment]
Can you pass the queryBuilder via the closure instead? I think that's how we do it elsewhere. If there's definitely no way of getting queryBuilder then I'm okay with passing a details object to the function, where `queryBuilder` is the only key currently defined. (This way we can expand it in future without having to add additional arguments/changing the argument order/etc.)

**Comment by benjie** [comment]
(And yes, if this is the only way I'd consider a PR for it for sure 👍  )

**Comment by mathroc** [comment]
Hi @benjie, I’ve taken the time to update graphile on my project, thank you for all the work by the way!

Everything is working fine, I have my custom plugin to sort via foreign columns. Do you want to keep this issue open to add it? Maybe after #2

here is the plugin, it’s based on the compiled version and maybe not very well written but that could give someone a jump start if they’re interested

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

exports.default = function PgOrderByForeignTimestampColumnsPlugin(builder, { pgInflection: inflection }) {
  builder.hook("GraphQLEnumType:values", (values, { extend, pgIntrospectionResultsByKind: introspectionResultsByKind, pgSql: sql }, { scope: { isPgRowSortEnum, pgIntrospection: table } }) => {
    if (!isPgRowSortEnum || !table || table.kind !== "class") {
      return values;
    }
    const attrs = introspectionResultsByKind.attribute.filter(attr => attr.classId === table.id);

    const foreignKeys = introspectionResultsByKind.constraint
      .filter(con => con.type === "f")
      .filter(con => con.classId === table.id)
      .map(con => ({con, foreignTable: introspectionResultsByKind.classById[con.foreignClassId]}))
      .map(({con, foreignTable}) => ({
        con,
        foreignTable,
        foreignAttrs: introspectionResultsByKind.attribute.filter(attr => attr.classId === foreignTable.id)
      }))
      .map(({con, foreignTable, foreignAttrs}) => ({
        con, foreignTable, foreignAttrs, sortableForeignAttrs: foreignAttrs
          .filter(attr => attr.type.type === "b")
          .filter(attr => attr.type.name === "timestamptz")
      }))
      .filter(({sortableForeignAttrs}) => sortableForeignAttrs.length > 0);

    return extend(values, foreignKeys.reduce((memo, foreignKey) => {
      return foreignKey.sortableForeignAttrs.reduce((memo, ra) => {
        [true, false].reduce((memo, dir) => {
          const fkAttrs = foreignKey.con.keyAttributeNums.map((num, i) => ({
            local: attrs.filter(a => a.num === num)[0].name,
            remote: foreignKey.foreignAttrs.filter(a => a.num === foreignKey.con.foreignKeyAttributeNums[i])[0].name,
          }));
          const ascFieldName = inflection.orderByEnum(
            [...fkAttrs.map(fkAttr => fkAttr.local), ra.name].join("-"),
            dir,
            table.name,
            table.namespaceName
          );
          memo[ascFieldName] = {
            value: {
              alias: ascFieldName.toLowerCase(),
              specs: [[({ queryBuilder }) => sql.fragment`(
                select ${sql.identifier(ra.name)}
                from ${sql.identifier(foreignKey.foreignTable.namespace.name, foreignKey.foreignTable.name)}
                where ${sql.join(fkAttrs.map(
                  fkAttr => sql.fragment`
                    ${sql.identifier(foreignKey.foreignTable.namespace.name, foreignKey.foreignTable.name, fkAttr.remote)} =
                    ${queryBuilder.getTableAlias()}.${sql.identifier(fkAttr.local)}
                  `
                ), ' AND ')}
                )`, dir]]
            }
          };
          return memo;
        }, memo)
        return memo;
      }, memo)
    }, {}));
  });
};
```

**Comment by benjie** [comment]
If you could put it into it's own repo where it can receive issues and PRs and add it to the wiki I think that would be the best for now:

https://github.com/postgraphql/postgraphql/wiki/v4-plugins

(Feel free to publish it to npm so that people can use it using the `--append-plugins` option: https://www.graphile.org/postgraphile/extending/#loading-additional-plugins )

**Comment by mattbretl** [comment]
Plugin available: https://github.com/graphile-contrib/pg-order-by-related

**Comment by benjie** [comment]
👍👍

**Comment by benjie** [comment]
Could you add it to https://www.graphile.org/postgraphile/community-plugins/ please?

**Comment by mathroc** [comment]
awesome, thank you @mattbretl , I'm trying that right now ;)

**Comment by mattbretl** [comment]
Cool - I don't think `postgraphile@4.1.0` has been published to npm yet, so you'll need to use `postgraphile@4.1.0-rc.0`.
